import type { ItemDefinitionInput } from "@/types";

export const eliteAcademyItems: ItemDefinitionInput[] = [
  {
    id: "ea-item-canteen-coffee",
    name: "Canteen Coffee",
    description: "Bitter vending-machine coffee. Takes the edge off a long study night.",
    kind: "consumable",
    slot: "none",
    rarity: "common",
    value: 50,
    icon: "coffee",
    useEffect: { stressRelief: 8 },
  },
  {
    id: "ea-item-study-guide",
    name: "Annotated Study Guide",
    description: "A meticulously marked-up guide passed between upperclassmen. Handle carefully — it's currency.",
    kind: "quest",
    slot: "none",
    rarity: "uncommon",
    value: 300,
    icon: "book-open",
  },
  {
    id: "ea-item-hairpin",
    name: "Plain Silver Hairpin",
    description: "An unremarkable hairpin. Someone dropped it near the student council room.",
    kind: "quest",
    slot: "none",
    rarity: "common",
    value: 0,
    icon: "sparkle",
  },
  {
    id: "ea-item-private-points-voucher",
    name: "Private Point Voucher (500)",
    description: "Redeemable school currency. What you do with it says a lot about you.",
    kind: "consumable",
    slot: "none",
    rarity: "uncommon",
    value: 500,
    icon: "coins",
  },
  {
    id: "ea-item-notebook-photocopy",
    name: "Photocopied Notebook Page",
    description: "A single page copied from someone's private notes. Reading it feels like trespassing.",
    kind: "quest",
    slot: "none",
    rarity: "rare",
    value: 0,
    icon: "file-text",
  },
  {
    id: "ea-item-founders-record",
    name: "The Founders' Ledger Page",
    description: "A single preserved page from the academy's founding ledger. It describes a ranking system built specifically to reward the classes willing to climb from nothing — word for word, the same philosophy behind this year's unexplained point penalty.",
    kind: "quest",
    slot: "none",
    rarity: "legendary",
    value: 0,
    icon: "scroll",
  },
];
