import type { NpcDefinitionInput } from "@/types";

/**
 * Elite Academy — Class 1-D major NPCs.
 * All characters are original creations; any resemblance to existing works is coincidental
 * atmospheric homage, not reproduction.
 */
export const eliteAcademyNpcs: NpcDefinitionInput[] = [
  {
    id: "ea-rei",
    worldId: "elite-academy",
    fullName: "Rei Kagayama",
    shortName: "Rei",
    role: "rival",
    personality: "Ice-calm class representative who treats every interaction like a transaction.",
    motivation: "Believes only measurable results earn respect — climbing to Class A is proof of worth.",
    secret: "Comes from Class A's outer reserve list; one bad exam and she is demoted, which she has told no one.",
    strength: "Analysis and cold logic under pressure.",
    weakness: "Cannot admit fault publicly; will double down rather than lose face.",
    speechStyle: "Clipped, formal, precise. Rarely uses contractions.",
    portraitColor: "#2b2b2b",
    portraitGlyph: "user",
    hairColor: "black",
    hairstyle: "long",
    eyeColor: "gray",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "cold", "smirk", "shocked", "thinking", "frown"],
    romanceable: true,
    canJoinParty: false,
    personalQuestId: "ea-q-rei-reserve",
  },
  {
    id: "ea-souta",
    worldId: "elite-academy",
    fullName: "Souta Ibaraki",
    shortName: "Souta",
    role: "classmate",
    personality: "Loud, easygoing, secretly terrified of being useless to the class.",
    motivation: "Wants to matter to somebody after years of being overlooked at home.",
    secret: "Failed the entrance placement exam and was let in on a discretionary slot.",
    strength: "Reads the room fast; makes people comfortable.",
    weakness: "Panics and lies under direct pressure.",
    speechStyle: "Casual, joking, over-explains when nervous.",
    portraitColor: "#8a6d3b",
    portraitGlyph: "smile",
    hairColor: "brown",
    hairstyle: "short",
    eyeColor: "hazel",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smile", "laugh", "worried", "shocked"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ea-yuzuki",
    worldId: "elite-academy",
    fullName: "Yuzuki Hoshino",
    shortName: "Yuzuki",
    role: "romance",
    personality: "Gentle, observant, quietly strategic — everyone underestimates her.",
    motivation: "Wants to prove that kindness is not the same as weakness.",
    secret: "Keeps a private notebook logging every classmate's behavioral patterns.",
    strength: "Empathy and quiet perception; people confide in her.",
    weakness: "Avoids confrontation even when she is right.",
    speechStyle: "Soft-spoken, thoughtful pauses, precise word choice.",
    portraitColor: "#5b4a7a",
    portraitGlyph: "heart",
    hairColor: "ash-blonde",
    hairstyle: "wavy",
    eyeColor: "steel-blue",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smile", "blush", "worried", "thinking", "sad"],
    romanceable: true,
    canJoinParty: false,
    personalQuestId: "ea-q-yuzuki-notebook",
  },
  {
    id: "ea-daichi",
    worldId: "elite-academy",
    fullName: "Daichi Onodera",
    shortName: "Daichi",
    role: "authority",
    personality: "Charismatic student council vice-president, impossible to read.",
    motivation: "Uses the council as leverage to gather leverage on everyone else.",
    secret: "Sells early exam-format hints to select students for private points.",
    strength: "Manipulation and information control.",
    weakness: "Overconfident; underestimates people he considers 'ordinary.'",
    speechStyle: "Warm, magnetic, faintly condescending.",
    portraitColor: "#7a1f1f",
    portraitGlyph: "crown",
    hairColor: "auburn",
    hairstyle: "short",
    eyeColor: "amber",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smile", "smirk", "cold", "angry"],
    romanceable: false,
    canJoinParty: false,
    personalQuestId: "ea-q-daichi-leak",
  },
  {
    id: "ea-nao",
    worldId: "elite-academy",
    fullName: "Nao Ichijou",
    shortName: "Nao",
    role: "classmate",
    personality: "Blunt, competitive, secretly the strongest academic mind in 1-D.",
    motivation: "Refuses to be defined by her older sister's reputation in Class A.",
    secret: "Deliberately under-performs on some exams to avoid council attention.",
    strength: "Raw intelligence, pattern recognition.",
    weakness: "Alienates people with bluntness; poor at reading emotional subtext.",
    speechStyle: "Terse, factual, dry humor.",
    portraitColor: "#1f4a3d",
    portraitGlyph: "book",
    hairColor: "black",
    hairstyle: "ponytail",
    eyeColor: "dark-brown",
    skinTone: "olive",
    expressionsAvailable: ["neutral", "smirk", "frown", "shocked", "thinking"],
    romanceable: true,
    canJoinParty: false,
  },
  {
    id: "ea-kenta",
    worldId: "elite-academy",
    fullName: "Kenta Mabuchi",
    shortName: "Kenta",
    role: "classmate",
    personality: "Quiet loner, physically strongest in class, avoids conflict.",
    motivation: "Transferred after a fight at his last school; trying to disappear.",
    secret: "Still sends money home anonymously to the family of the student he hurt.",
    strength: "Physical composure, reliable under real danger.",
    weakness: "Shuts down completely when accused of anything.",
    speechStyle: "Minimal, direct, long silences.",
    portraitColor: "#333333",
    portraitGlyph: "shield",
    hairColor: "charcoal",
    hairstyle: "buzzcut",
    eyeColor: "onyx",
    skinTone: "deep",
    expressionsAvailable: ["neutral", "frown", "worried", "determined"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ea-hikari",
    worldId: "elite-academy",
    fullName: "Hikari Endo",
    shortName: "Hikari",
    role: "neutral",
    personality: "Cheerful gossip hub who knows everything about everyone.",
    motivation: "Trades information for social standing; craves being 'in the loop.'",
    secret: "Is the anonymous source behind most of the rumors that hurt Rei's reputation.",
    strength: "Information network across all four classes.",
    weakness: "Can't keep a secret longer than a day.",
    speechStyle: "Fast, chatty, punctuates with questions.",
    portraitColor: "#b3833b",
    portraitGlyph: "message-circle",
    hairColor: "ash-blonde",
    hairstyle: "twintails",
    eyeColor: "hazel",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "smile", "laugh", "shocked", "smirk"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ea-fumiko",
    worldId: "elite-academy",
    fullName: "Fumiko Arase",
    shortName: "Ms. Arase",
    role: "mentor",
    personality: "Homeroom teacher, unreadable, tests students more than she teaches them.",
    motivation: "Believes the school's ranking system reveals true character under pressure.",
    secret: "Personally lobbied to have the player placed in Class 1-D instead of 1-A.",
    strength: "Total institutional knowledge; sees everything happening in her class.",
    weakness: "Will not intervene even when a student is being set up to fail.",
    speechStyle: "Flat, clinical, occasionally cutting.",
    portraitColor: "#111111",
    portraitGlyph: "eye",
    hairColor: "silver",
    hairstyle: "short",
    eyeColor: "gray",
    skinTone: "light",
    expressionsAvailable: ["neutral", "cold", "smirk", "thinking"],
    romanceable: false,
    canJoinParty: false,
    codexUnlockedByDefault: true,
  },
];
