import type { SceneInput } from "@/types";

const W = "elite-academy" as const;
const C = "ea-ch1" as const;

export const eliteAcademyScenes: SceneInput[] = [
  /* ------------------------------- Opening ------------------------------- */
  {
    id: "ea-scene-arrival",
    worldId: W,
    chapterId: C,
    title: "Arrival",
    startNode: "n1",
    background: "academy-gate",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The gate to the Advanced Integrated Academy is taller than the brochure made it look. A government-funded school that promises everything, if you can survive the ranking system underneath it.",
        next: "n2",
        speakerId: undefined,
        speakerName: undefined,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ea-fumiko",
        speakerName: "Ms. Arase",
        expression: "neutral",
        text: "You're the transfer into 1-C. Don't mistake this for a fresh start — every class here is already a hierarchy. You're just choosing where you enter it.",
        next: "n3",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-arrived" }, { type: "unlockCodex", entryId: "ea-codex-academy" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        speakerId: "ea-fumiko",
        speakerName: "Ms. Arase",
        expression: "cold",
        text: "Private points buy comfort. Class points decide whether your whole class gets to keep existing as it is. Figure out fast which one you're actually playing for.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "changeLocation", mapId: "ea-map-classroom", spawnId: "fromHallway" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- NPC introductions ---------------------------- */
  {
    id: "ea-scene-arase-intro",
    worldId: W,
    chapterId: C,
    title: "Homeroom",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-fumiko",
        speakerName: "Ms. Arase",
        expression: "neutral",
        text: "Settling in? Don't. Comfort here is a liability.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-arase" }, { type: "unlockCodex", entryId: "ea-codex-arase" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: undefined,
        expression: "neutral",
        isInnerMonologue: false,
        isInterruption: false,
        text: "How do you want to play this?",
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"I'm here to do the work.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-fumiko", axis: "respect", delta: 6 }],
            importantChoice: false,
          },
          {
            id: "c2",
            text: "\"I'm here to figure out how this place actually works first.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            requirementLabel: undefined,
            effects: [{ type: "modifyRelationship", npcId: "ea-fumiko", axis: "trust", delta: 4 }, { type: "modifyStat", stat: "perception", delta: 1 }],
            importantChoice: false,
          },
          {
            id: "c3",
            text: "Say nothing and let her keep talking.",
            isSilence: true,
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-fumiko", axis: "suspicion", delta: 2 }],
            importantChoice: false,
          },
        ],
      },
    ],
  },
  {
    id: "ea-scene-rei-intro",
    worldId: W,
    chapterId: C,
    title: "Rei Kagayama",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "cold",
        text: "You're the transfer. I've already read your placement file. Underwhelming, but not disqualifying.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-rei" }, { type: "unlockCodex", entryId: "ea-codex-rei" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: undefined,
        expression: "neutral",
        text: "She's class representative and treats the introduction like an audit.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"Read anything interesting?\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-rei", axis: "respect", delta: 3 }],
            goTo: "n3",
            importantChoice: false,
          },
          {
            id: "c2",
            text: "Challenge her tone directly.",
            requirementLabel: "Requires Courage 6",
            conditions: [{ type: "minStat", stat: "courage", value: 6 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-rei", axis: "rivalry", delta: 5 }, { type: "modifyRelationship", npcId: "ea-rei", axis: "respect", delta: 4 }],
            goTo: "n4",
            importantChoice: false,
          },
          {
            id: "c3",
            text: "Notice how her file talk doesn't quite match her file.",
            requirementLabel: "Requires Perception 7 (hidden)",
            conditions: [{ type: "minStat", stat: "perception", value: 7 }],
            hiddenIfUnmet: true,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "setFlag", flag: "ea-flag-noticed-rei-discrepancy" }, { type: "startQuest", questId: "ea-q-rei-reserve" }],
            goTo: "n5",
            importantChoice: false,
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "smirk",
        text: "That depends on whether you're worth the read a second time. Prove it in the first exam.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "shocked",
        text: "...Fine. Most people don't push back. Keep that up and I might have to actually pay attention to you.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n5",
        expression: "neutral",
        isInnerMonologue: true,
        text: "She talks about the reserve list like it's beneath her — but her own transcript has the exact profile of someone clinging to a spot, not commanding one. One bad exam and she'd fall out of Class A's shadow roster entirely. She hasn't told anyone that.",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ea-codex-rei-secret" }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-rei-secret-followup",
    worldId: W,
    chapterId: C,
    title: "What You Know About Rei",
    startNode: "n1",
    altEntryNodes: ["n1", "afterward"],
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: false,
        text: "You could bring up what you noticed about Rei's standing. Or leave it alone.",
        isInterruption: false,
        effects: [],
        conditions: [{ type: "flag", flag: "ea-flag-noticed-rei-discrepancy" }, { type: "missingFlag", flag: "ea-q-rei-reserve-resolved" }],
        choices: [
          {
            id: "c1",
            text: "Tell her you know, and that it doesn't change anything between you.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-q-rei-reserve-resolved" },
              { type: "completeQuest", questId: "ea-q-rei-reserve", outcome: "trusted" },
              { type: "modifyRelationship", npcId: "ea-rei", axis: "trust", delta: 25 },
              { type: "modifyRelationship", npcId: "ea-rei", axis: "affection", delta: 10 },
            ],
            goTo: "good",
          },
          {
            id: "c2",
            text: "Keep it to yourself as leverage, just in case.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-q-rei-reserve-resolved" },
              { type: "completeQuest", questId: "ea-q-rei-reserve", outcome: "leveraged" },
              { type: "setFlag", flag: "ea-flag-holds-rei-secret" },
            ],
          },
        ],
      },
      {
        id: "good",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "shocked",
        text: "...You knew. And you didn't use it. I don't know what to do with that, honestly.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "afterward",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "neutral",
        text: "Was there something else?",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-souta-intro",
    worldId: W,
    chapterId: C,
    title: "Souta Ibaraki",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-souta",
        speakerName: "Souta",
        expression: "smile",
        text: "Oh hey, new guy! Or— sorry, didn't ask. New person! Welcome to the bottom of the food chain, population: us.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-souta" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ea-souta",
        speakerName: "Souta",
        expression: "worried",
        text: "Listen — between us — you didn't hear this from me, but there's a study sheet going around for the placement quiz. Half the class already has it. You want in?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"Sure, share it.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [
              { type: "addItem", itemId: "ea-item-study-guide", quantity: 1 },
              { type: "modifyRelationship", npcId: "ea-souta", axis: "trust", delta: 6 },
              { type: "setFlag", flag: "ea-flag-took-cheat-sheet" },
            ],
            importantChoice: true,
            goTo: "n3",
          },
          {
            id: "c2",
            text: "\"That's cheating, Souta. Ms. Arase should hear about this.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [
              { type: "modifyRelationship", npcId: "ea-souta", axis: "trust", delta: -10 },
              { type: "modifyRelationship", npcId: "ea-souta", axis: "fear", delta: 8 },
              { type: "modifyRelationship", npcId: "ea-fumiko", axis: "respect", delta: 3 },
              { type: "setFlag", flag: "ea-flag-reported-souta" },
            ],
            importantChoice: true,
            goTo: "n4",
          },
          {
            id: "c3",
            text: "\"Not interested — but I won't say anything either.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-souta", axis: "respect", delta: 5 }],
            importantChoice: true,
            goTo: "n5",
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-souta",
        speakerName: "Souta",
        expression: "laugh",
        text: "Knew I liked you. Just— seriously, don't tell Rei. She'd report her own shadow if it broke a rule.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        speakerId: "ea-souta",
        speakerName: "Souta",
        expression: "shocked",
        text: "W-wait, I was kidding! ...You're not kidding. Okay. Okay, noted. Great first impression, me.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n5",
        speakerId: "ea-souta",
        speakerName: "Souta",
        expression: "smile",
        text: "Honestly? Fair. I respect that more than if you'd just taken it. Most people don't leave you an out.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-nao-intro",
    worldId: W,
    chapterId: C,
    title: "Nao Ichijou",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "neutral",
        text: "You're staring at the ranking board like it means something today. It doesn't. Come back after the first exam.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-nao" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: undefined,
        expression: "thinking",
        text: "She said that without looking up from her book once.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"You sound like you've done this before.\"",
            requirementLabel: "Requires Perception 5",
            conditions: [{ type: "minStat", stat: "perception", value: 5 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-nao", axis: "respect", delta: 6 }],
            goTo: "n3",
            importantChoice: false,
          },
          {
            id: "c2",
            text: "\"Noted. Thanks.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-nao", axis: "trust", delta: 2 }],
            goTo: "n4",
            importantChoice: false,
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "smirk",
        text: "...Sharper than the last one. Fine. If you want actual information instead of small talk, find me in the library.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "neutral",
        text: "Mm.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-kenta-intro",
    worldId: W,
    chapterId: C,
    title: "Kenta Mabuchi",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-kenta",
        speakerName: "Kenta",
        expression: "neutral",
        text: "...",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-kenta" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: undefined,
        expression: "neutral",
        text: "He nods once. That might be the whole conversation, if you let it be.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Nod back and leave him be.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: true,
            effects: [{ type: "modifyRelationship", npcId: "ea-kenta", axis: "respect", delta: 4 }],
            goTo: "n3",
            importantChoice: false,
          },
          {
            id: "c2",
            text: "\"You're not much of a talker.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-kenta", axis: "trust", delta: -2 }],
            goTo: "n4",
            importantChoice: false,
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-kenta",
        speakerName: "Kenta",
        expression: "neutral",
        text: "...Thanks.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        speakerId: "ea-kenta",
        speakerName: "Kenta",
        expression: "frown",
        text: "No. I'm not.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-kenta-gym",
    worldId: W,
    chapterId: C,
    title: "Gym",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-kenta",
        speakerName: "Kenta",
        expression: "neutral",
        text: "You train, or you're just here to watch?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"Spar with me.\"",
            requirementLabel: "Requires Courage 5",
            conditions: [{ type: "minStat", stat: "courage", value: 5 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [
              { type: "modifyStat", stat: "combat", delta: 1 },
              { type: "modifyRelationship", npcId: "ea-kenta", axis: "respect", delta: 8 },
            ],
            importantChoice: false,
          },
          {
            id: "c2",
            text: "\"Just watching. You're intense about this.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-kenta", axis: "trust", delta: 2 }],
          },
        ],
      },
    ],
  },
  {
    id: "ea-scene-yuzuki-intro",
    worldId: W,
    chapterId: C,
    title: "Yuzuki Hoshino",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "smile",
        text: "You looked a little lost, so — hi. I'm Yuzuki. If you ever need to know who to actually trust in here, I probably have opinions.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-yuzuki" }, { type: "unlockCodex", entryId: "ea-codex-yuzuki" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: undefined,
        expression: "neutral",
        text: "Something about the way she says it makes it sound like an offer, not small talk.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"I might take you up on that.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-yuzuki", axis: "affection", delta: 4 }, { type: "modifyRelationship", npcId: "ea-yuzuki", axis: "trust", delta: 3 }],
          },
          {
            id: "c2",
            text: "\"Why would you help a total stranger?\"",
            requirementLabel: "Requires Deception 4",
            conditions: [{ type: "minStat", stat: "deception", value: 4 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-yuzuki", axis: "respect", delta: 5 }],
            goTo: "n3",
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "thinking",
        text: "...Good question. Maybe I just like knowing things before everyone else. Is that so bad?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-daichi-intro",
    worldId: W,
    chapterId: C,
    title: "Daichi Onodera",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "smile",
        text: "1-C's new arrival, in the flesh. Word travels fast around here — I make sure it does. Anything you need, my door's open.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-daichi" }, { type: "unlockCodex", entryId: "ea-codex-daichi" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: undefined,
        expression: "neutral",
        text: "Everything about him is calibrated to be likable. That's exactly what makes it hard to trust.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-hikari-hub",
    worldId: W,
    chapterId: C,
    title: "Hikari Endo",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ea-hikari",
        speakerName: "Hikari",
        expression: "smile",
        text: "New face! Okay, fast download: Rei's terrifying but fair, Daichi's charming but don't owe him anything, and Kenta transferred mid-year for reasons nobody will say out loud. You're welcome.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-met-hikari" }, { type: "unlockCodex", entryId: "ea-codex-hikari" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- Ranking board / penalty ---------------------------- */
  {
    id: "ea-scene-ranking-board",
    worldId: W,
    chapterId: C,
    title: "Class Ranking Board",
    startNode: "gate",
    altEntryNodes: ["gate", "n1", "seen"],
    nodes: [
      {
        id: "gate",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The board updates class points in real time. Right now, 1-C sits comfortably in third.",
        isInterruption: false,
        effects: [],
        conditions: [{ type: "missingFlag", flag: "ea-flag-met-arase" }],
        choices: [],
        next: undefined,
      },
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The board updates class points in real time. Right now, 1-C sits comfortably in third — until you notice the number just changed.",
        conditions: [{ type: "flag", flag: "ea-flag-met-arase" }, { type: "missingFlag", flag: "ea-flag-penalty-revealed" }],
        next: "n2",
        isInterruption: false,
        effects: [],
        choices: [],
      },
      {
        id: "n2",
        expression: "shocked",
        isInnerMonologue: true,
        text: "1-C: −120 points. No exam happened today. No announcement. Just a silent deduction sitting on the board like it's daring someone to ask why.",
        next: "n3",
        isInterruption: false,
        effects: [
          { type: "setFlag", flag: "ea-flag-penalty-revealed" },
          { type: "startQuest", questId: "ea-q-daichi-leak" },
          { type: "unlockCodex", entryId: "ea-codex-class-points" },
          { type: "unlockAchievement", achievementId: "ach-first-mystery" },
        ],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "cold",
        text: "You saw it too. Faculty won't explain silent penalties — they never do. Someone in the council did this, or let it happen. Find out which, and I'll owe you.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "seen",
        expression: "neutral",
        isInnerMonologue: true,
        text: "1-C: 720 points, holding steady in third. For now.",
        isInterruption: false,
        effects: [],
        conditions: [{ type: "flag", flag: "ea-flag-penalty-revealed" }],
        choices: [],
      },
    ],
  },

  /* ---------------------------- Investigation route ---------------------------- */
  {
    id: "ea-scene-nao-library",
    worldId: W,
    chapterId: C,
    title: "Library — Nao",
    startNode: "locked",
    altEntryNodes: ["locked", "n1"],
    nodes: [
      {
        id: "locked",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "neutral",
        text: "Studying. Come back when you have an actual question.",
        conditions: [{ type: "missingFlag", flag: "ea-flag-penalty-revealed" }],
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
      },
      {
        id: "n1",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "thinking",
        text: "The penalty. You're here about the penalty.",
        next: "n2",
        conditions: [{ type: "flag", flag: "ea-flag-penalty-revealed" }],
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [],
      },
      {
        id: "n2",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "smirk",
        text: "Three people in this class already knew the last exam's format before it was posted. That's not luck. That's a leak — and leaks cost points when they're traced back to the source class.",
        isInterruption: false,
        effects: [
          { type: "setFlag", flag: "ea-flag-clue-format-leak" },
          { type: "unlockCodex", entryId: "ea-codex-private-points" },
        ],
        choices: [],
        conditions: [],
        next: "n3",
      },
      {
        id: "n3",
        speakerId: "ea-nao",
        speakerName: "Nao",
        expression: "neutral",
        text: "Council room sells information. Ask yourself who in this school would have both the access and the nerve.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-investigating-daichi" }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-hikari-courtyard",
    worldId: W,
    chapterId: C,
    title: "Courtyard — Hikari",
    startNode: "n1",
    altEntryNodes: ["n1", "n1-fallback"],
    nodes: [
      {
        id: "n1",
        speakerId: "ea-hikari",
        speakerName: "Hikari",
        expression: "smirk",
        text: "Ohhh, you're digging into the point drop? Careful — Daichi's the one who'd know first if someone started asking around.",
        isInterruption: false,
        effects: [],
        conditions: [{ type: "flag", flag: "ea-flag-investigating-daichi" }],
        choices: [
          {
            id: "c1",
            text: "\"Do you think it was him?\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "setFlag", flag: "ea-flag-clue-hikari-suspicion" }, { type: "modifyRelationship", npcId: "ea-hikari", axis: "trust", delta: 3 }, { type: "sendMessage", npcId: "ea-hikari", messageId: "ea-msg-hikari-quiet" }],
            goTo: "n2",
          },
          {
            id: "c2",
            text: "Push for who has Yuzuki's missing notebook instead.",
            conditions: [{ type: "flag", flag: "ea-flag-yuzuki-notebook-missing" }],
            hiddenIfUnmet: true,
            isBluff: false,
            isSilence: false,
            effects: [
              { type: "setFlag", flag: "ea-flag-hikari-has-notebook-known" },
              { type: "modifyRelationship", npcId: "ea-hikari", axis: "suspicion", delta: 10 },
            ],
            goTo: "n3",
          },
        ],
        next: undefined,
      },
      {
        id: "n1-fallback",
        speakerId: "ea-hikari",
        speakerName: "Hikari",
        expression: "smile",
        text: "You didn't hear it from me, but everyone's a little scared to say Daichi's name too loud.",
        isInterruption: false,
        effects: [],
        conditions: [{ type: "missingFlag", flag: "ea-flag-investigating-daichi" }],
        choices: [],
      },
      {
        id: "n2",
        speakerId: "ea-hikari",
        speakerName: "Hikari",
        expression: "worried",
        text: "I didn't say that. I definitely didn't say that. But — a couple of 1-A kids have been way too calm about exams lately, and calm costs money around here.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-clue-1a-buyers" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        speakerId: "ea-hikari",
        speakerName: "Hikari",
        expression: "shocked",
        text: "...Okay, fine, yes, it might be sitting in my bag. I was going to give it back! Eventually! Probably!",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-daichi-investigate",
    worldId: W,
    chapterId: C,
    title: "Confronting Daichi",
    startNode: "stonewall",
    altEntryNodes: ["stonewall", "n1"],
    nodes: [
      {
        id: "stonewall",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "smile",
        text: "Something on your mind? You've got that look people get right before they accuse me of something they can't prove.",
        conditions: [{ type: "missingFlag", flag: "ea-flag-clue-format-leak" }],
        isInterruption: false,
        effects: [],
        choices: [],
      },
      {
        id: "n1",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "smirk",
        text: "The point penalty. You've been asking around — Nao, Hikari, half the library. Go on, then. Ask me directly.",
        next: "n2",
        conditions: [{ type: "flag", flag: "ea-flag-clue-format-leak" }],
        isInterruption: false,
        effects: [],
        choices: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to play this?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"You sold the exam format. I have enough to prove it.\"",
            requirementLabel: "Requires clue: 1-A buyers",
            conditions: [{ type: "flag", flag: "ea-flag-clue-1a-buyers" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-daichi-cornered" },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "fear", delta: 15 },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "respect", delta: 8 },
            ],
            goTo: "n3",
          },
          {
            id: "c2",
            text: "Bluff — claim you already reported him to faculty.",
            isBluff: true,
            requirementLabel: "Bluff — Deception check",
            conditions: [{ type: "minStat", stat: "deception", value: 5 }],
            hiddenIfUnmet: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-daichi-bluffed" },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "suspicion", delta: 10 },
            ],
            goTo: "n4",
          },
          {
            id: "c3",
            text: "\"I don't have proof yet. But I will.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "modifyRelationship", npcId: "ea-daichi", axis: "respect", delta: 3 }],
            goTo: "n5",
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "cold",
        text: "...Fine. What do you want. Everyone wants something — that's the one rule of this school I never see broken.",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ea-codex-daichi-secret" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "shocked",
        text: "You— reported it? To who, Arase? She'd have called me in already. ...You're bluffing. Bold. I'll remember that.",
        isInterruption: false,
        effects: [{ type: "modifyRelationship", npcId: "ea-daichi", axis: "suspicion", delta: 5 }],
        choices: [],
        conditions: [],
      },
      {
        id: "n5",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "smile",
        text: "Confidence without cards to back it up. I almost respect that. Almost.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- Yuzuki notebook subplot ---------------------------- */
  {
    id: "ea-scene-yuzuki-rooftop",
    worldId: W,
    chapterId: C,
    title: "Rooftop — Yuzuki",
    startNode: "n1",
    altEntryNodes: ["n1", "revisit", "afterward"],
    nodes: [
      {
        id: "n1",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "worried",
        text: "Can I— ask you something? My notebook is missing. It's just observations, habits, things people let slip. If it gets out, I don't think some of these friendships survive it.",
        next: "n2",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-yuzuki-notebook-missing" }, { type: "startQuest", questId: "ea-q-yuzuki-notebook" }],
        choices: [],
        conditions: [{ type: "missingFlag", flag: "ea-flag-yuzuki-notebook-missing" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"I'll help you find it. Quietly.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-yuzuki", axis: "trust", delta: 8 }, { type: "modifyRelationship", npcId: "ea-yuzuki", axis: "affection", delta: 5 }],
          },
          {
            id: "c2",
            text: "\"Why do you even keep something like that?\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ea-yuzuki", axis: "trust", delta: -3 }],
            goTo: "n3",
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "sad",
        text: "...Because being liked isn't the same as being safe here. I needed to know who was actually on my side. I guess that sounds paranoid.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "revisit",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "smile",
        text: "Any leads on the notebook?",
        conditions: [{ type: "flag", flag: "ea-flag-yuzuki-notebook-missing" }, { type: "missingFlag", flag: "ea-flag-notebook-resolved" }],
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        choices: [
          {
            id: "c1",
            text: "\"It's Hikari. I can get it back quietly.\"",
            conditions: [{ type: "flag", flag: "ea-flag-hikari-has-notebook-known" }],
            hiddenIfUnmet: true,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-notebook-resolved" },
              { type: "setFlag", flag: "ea-flag-notebook-protected" },
              { type: "modifyRelationship", npcId: "ea-yuzuki", axis: "trust", delta: 15 },
              { type: "modifyRelationship", npcId: "ea-yuzuki", axis: "affection", delta: 10 },
              { type: "unlockAchievement", achievementId: "ach-nobody-left-behind" },
            ],
            goTo: "resolved-good",
          },
          {
            id: "c2",
            text: "Sell what you know about the notebook's location to Daichi for private points.",
            conditions: [{ type: "flag", flag: "ea-flag-hikari-has-notebook-known" }],
            hiddenIfUnmet: true,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-notebook-resolved" },
              { type: "setFlag", flag: "ea-flag-betrayed-yuzuki" },
              { type: "addItem", itemId: "ea-item-private-points-voucher", quantity: 2 },
              { type: "modifyRelationship", npcId: "ea-yuzuki", axis: "trust", delta: -40 },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "loyalty", delta: 10 },
              { type: "unlockAchievement", achievementId: "ach-broken-promise" },
            ],
            goTo: "resolved-bad",
          },
          {
            id: "c3",
            text: "\"Nothing yet. Still looking.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [],
          },
        ],
      },
      {
        id: "resolved-good",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "blush",
        text: "You didn't have to do that carefully. You could've just taken the credit for exposing Hikari. ...Thank you. Really.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "resolved-bad",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "shocked",
        text: "You— you knew? This whole time? ...I understand now. I really do. I won't make that mistake again.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "afterward",
        speakerId: "ea-yuzuki",
        speakerName: "Yuzuki",
        expression: "smile",
        text: "The wind's nice up here, isn't it. Thanks again for everything.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- Special Exam: Consensus Trial ---------------------------- */
  {
    id: "ea-scene-consensus-trial",
    worldId: W,
    chapterId: C,
    title: "Special Exam: The Consensus Trial",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The special exam rules post overnight: each class gets a fixed pool of 'resource points' to distribute among its own students however it likes. Whoever ends up with the lowest individual total from their own class fails, regardless of the class's overall score. Somewhere in 1-C, someone has been secretly told to sabotage the split.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ea-codex-consensus-trial" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "determined",
        text: "As representative, I'll propose the split. Equal shares protect everyone — but equal shares also protect whoever's sabotaging us, since it doesn't single anyone out.",
        next: "n3",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        expression: "neutral",
        text: "The room is watching you. This decision shapes what kind of 1-C survives the exam.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c-negotiate",
            text: "Propose a compromise: protect the weakest students first, let strong students absorb risk.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-exam-negotiate" },
              { type: "modifyRelationship", npcId: "ea-rei", axis: "respect", delta: 10 },
              { type: "modifyRelationship", npcId: "ea-yuzuki", axis: "trust", delta: 6 },
              { type: "changeClassPoints", classId: "class-1c", delta: 40 },
              { type: "changeReputation", delta: 10 },
            ],
            goTo: "n-negotiate",
          },
          {
            id: "c-investigate",
            text: "Use what you learned investigating Daichi to expose the sabotage before the vote.",
            requirementLabel: "Requires investigation clues gathered",
            conditions: [{ type: "flag", flag: "ea-flag-daichi-cornered" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-exam-exposed" },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "fear", delta: 20 },
              { type: "changeClassPoints", classId: "class-1c", delta: 60 },
              { type: "changeReputation", delta: 20 },
              { type: "unlockAchievement", achievementId: "ach-master-manipulator" },
            ],
            goTo: "n-exposed",
          },
          {
            id: "c-cooperate",
            text: "Back Rei's equal-split plan without question.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-exam-equal-split" },
              { type: "modifyRelationship", npcId: "ea-rei", axis: "loyalty", delta: 8 },
              { type: "changeClassPoints", classId: "class-1c", delta: 10 },
            ],
            goTo: "n-equal",
          },
          {
            id: "c-betray",
            text: "Quietly steer resources toward yourself — you can't trust this class not to sacrifice you first.",
            requirementLabel: "Requires Deception 6",
            conditions: [{ type: "minStat", stat: "deception", value: 6 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-exam-self-serve" },
              { type: "modifyStat", stat: "privatePoints", delta: 800 },
              { type: "changeClassPoints", classId: "class-1c", delta: -30 },
              { type: "modifyRelationship", npcId: "ea-rei", axis: "suspicion", delta: 15 },
              { type: "unlockAchievement", achievementId: "ach-five-steps-ahead" },
            ],
            goTo: "n-selfserve",
          },
        ],
      },
      {
        id: "n-negotiate",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "smile",
        text: "...That's a good plan. Better than mine, honestly. Don't expect me to say that twice.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
        next: "n-final",
      },
      {
        id: "n-exposed",
        speakerId: "ea-daichi",
        speakerName: "Daichi",
        expression: "angry",
        text: "You planned this. In front of everyone. ...Careful. This isn't over just because you won a round.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
        next: "n-final",
      },
      {
        id: "n-equal",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "neutral",
        text: "Predictable. Safe. It'll work — this time.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
        next: "n-final",
      },
      {
        id: "n-selfserve",
        speakerId: "ea-rei",
        speakerName: "Rei",
        expression: "cold",
        text: "Interesting. You'd let the rest of us take the risk. Noted. Filed away. I don't forget things like that.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
        next: "n-final",
      },
      {
        id: "n-final",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The exam results post the next morning. 1-C survives — but how it survives is now part of your reputation.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ea-flag-exam-complete" }, { type: "completeQuest", questId: "ea-q-daichi-leak" }, { type: "goToScene", sceneId: "ea-scene-chapter-decision" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- Chapter climax decision ---------------------------- */
  {
    id: "ea-scene-chapter-decision",
    worldId: W,
    chapterId: C,
    title: "What You Do With Daichi",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You know enough now to end Daichi's arrangement for good — or to keep it as leverage. Ms. Arase is waiting for your report on the penalty investigation.",
        next: "n2",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "What do you tell her?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Report Daichi in full. Let the school handle it properly.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-daichi-reported" },
              { type: "modifyRelationship", npcId: "ea-fumiko", axis: "respect", delta: 15 },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "rivalry", delta: 20 },
              { type: "changeReputation", delta: 15 },
              { type: "unlockAchievement", achievementId: "ach-class-savior" },
            ],
            goTo: "n-reported",
          },
          {
            id: "c2",
            text: "Say nothing concrete. Keep what you know as leverage over Daichi.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-daichi-leveraged" },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "fear", delta: 10 },
              { type: "modifyRelationship", npcId: "ea-fumiko", axis: "suspicion", delta: 10 },
              { type: "unlockAchievement", achievementId: "ach-unreadable" },
            ],
            goTo: "n-leverage",
          },
          {
            id: "c3",
            text: "Cover for him completely — protecting class unity matters more than punishing him.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ea-flag-daichi-covered" },
              { type: "modifyRelationship", npcId: "ea-daichi", axis: "loyalty", delta: 20 },
              { type: "modifyRelationship", npcId: "ea-fumiko", axis: "suspicion", delta: 15 },
            ],
            goTo: "n-covered",
          },
        ],
      },
      { id: "n-reported", speakerId: "ea-fumiko", speakerName: "Ms. Arase", expression: "neutral", text: "Clean. Documented. This is how you're supposed to do it — I almost don't believe you.", isInterruption: false, effects: [], choices: [], conditions: [], next: "n-close" },
      { id: "n-leverage", speakerId: "ea-fumiko", speakerName: "Ms. Arase", expression: "cold", text: "You're not telling me everything. I'll allow it — for now. Watch yourself.", isInterruption: false, effects: [], choices: [], conditions: [], next: "n-close" },
      { id: "n-covered", speakerId: "ea-fumiko", speakerName: "Ms. Arase", expression: "cold", text: "You're protecting someone. That's either loyalty or a mistake. Sometimes it's both.", isInterruption: false, effects: [], choices: [], conditions: [], next: "n-close" },
      {
        id: "n-close",
        expression: "neutral",
        isInnerMonologue: true,
        text: "That night, a message arrives on your school device from an unlisted contact: 'You handled that better than expected. I'll be watching what you do next.' No name attached.",
        isInterruption: false,
        effects: [
          { type: "setFlag", flag: "ea-flag-chapter1-complete" },
          { type: "unlockCodex", entryId: "ea-codex-watcher" },
          { type: "unlockAchievement", achievementId: "ach-hidden-truth" },
          { type: "sendMessage", npcId: "ea-daichi", messageId: "ea-msg-watcher" },
        ],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- Utility scenes ---------------------------- */
  {
    id: "ea-scene-study-here",
    worldId: W,
    chapterId: C,
    title: "Your Desk",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You spend a quiet stretch reviewing the day's material.",
        isInterruption: false,
        effects: [{ type: "modifyStat", stat: "intelligence", delta: 1 }, { type: "modifyStat", stat: "academicScore", delta: 3 }, { type: "modifyStat", stat: "stress", delta: 3 }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-study-minigame",
    worldId: W,
    chapterId: C,
    title: "Study Carrel",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You work through a set of logic drills — pattern sequences, evidence comparisons, timed recall. It's tedious, but it sharpens something.",
        isInterruption: false,
        effects: [{ type: "modifyStat", stat: "intelligence", delta: 1 }, { type: "modifyStat", stat: "perception", delta: 1 }, { type: "modifyStat", stat: "academicScore", delta: 5 }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-train-gym",
    worldId: W,
    chapterId: C,
    title: "Training",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You push through a training set until your arms shake.",
        isInterruption: false,
        effects: [{ type: "modifyStat", stat: "courage", delta: 1 }, { type: "modifyStat", stat: "discipline", delta: 1 }, { type: "modifyStat", stat: "stress", delta: -5 }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-rest",
    worldId: W,
    chapterId: C,
    title: "Rest",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You let the day end. Tomorrow, the board resets and the game continues.",
        isInterruption: false,
        effects: [{ type: "modifyStat", stat: "stress", delta: -15 }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-review-notes",
    worldId: W,
    chapterId: C,
    title: "Your Notes",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You flip back through what you've learned so far. The device's quest log has the rest, if you need a reminder.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-lunch-counter",
    worldId: W,
    chapterId: C,
    title: "Lunch Counter",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "You buy a coffee. Small comfort, honestly earned.",
        isInterruption: false,
        effects: [{ type: "modifyStat", stat: "privatePoints", delta: -50 }, { type: "addItem", itemId: "ea-item-canteen-coffee", quantity: 1 }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ea-scene-shop",
    worldId: W,
    chapterId: C,
    title: "Convenience Store",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: false,
        text: "What'll it be?",
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Buy Canteen Coffee — 50 points",
            requirementLabel: "Requires 50 Private Points",
            conditions: [{ type: "minStat", stat: "privatePoints", value: 50 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyStat", stat: "privatePoints", delta: -50 }, { type: "addItem", itemId: "ea-item-canteen-coffee", quantity: 1 }],
            goTo: "n1",
          },
          {
            id: "c2",
            text: "Leave",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [],
          },
        ],
      },
    ],
  },
  {
    id: "ea-scene-rooftop-monologue",
    worldId: W,
    chapterId: C,
    title: "The View",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "From up here, the whole campus looks orderly. Rankings, points, classes stacked neatly on top of each other. It's only up close that you can see how much of it is improvised.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
];
