import type { FloorDefinitionInput } from "@/types";

export const aincradFloors: FloorDefinitionInput[] = [
  {
    id: "floor-1",
    index: 1,
    name: "Sylvan Threshold",
    townMapId: "ai-map-town1",
    fieldMapId: "ai-map-field1",
    dungeonMapId: "ai-map-dungeon1",
    miniBossEnemyId: "en-alpha-timberwolf",
    floorBossEnemyId: "en-sylvan-guardian",
    uniqueItemId: "ai-item-floor1-unique",
    locked: false,
    description: "A forested first floor built to look survivable. Most of it even is.",
  },
  {
    id: "floor-2",
    index: 2,
    name: "Mistfallen Reach",
    townMapId: "ai-map-town2",
    fieldMapId: "ai-map-field2",
    dungeonMapId: "ai-map-dungeon2",
    miniBossEnemyId: "en-frostfang-alpha",
    floorBossEnemyId: "en-mistfallen-warden",
    uniqueItemId: "ai-item-mistguard-blade",
    unlockFlag: "ai-flag-floor1-cleared",
    locked: true,
    description: "Cold highlands wrapped in permanent fog. Fewer players make it this far.",
  },
  {
    id: "floor-3",
    index: 3,
    name: "Ashen Hollow",
    townMapId: "ai-map-town3",
    fieldMapId: "ai-map-field3",
    dungeonMapId: "ai-map-dungeon3",
    miniBossEnemyId: "en-molten-sentinel",
    floorBossEnemyId: "en-ashen-hollow-king",
    uniqueItemId: "ai-item-floorguard-mail",
    unlockFlag: "ai-flag-floor2-cleared",
    locked: true,
    description: "Volcanic rock and old grief. Someone still keeps a vigil at its dungeon gate.",
  },
  {
    id: "floor-4",
    index: 4,
    name: "Verdant Spire",
    townMapId: "ai-map-town4",
    fieldMapId: "ai-map-field4",
    miniBossEnemyId: "en-spire-ape",
    floorBossEnemyId: "en-verdant-warden",
    uniqueItemId: "ai-item-forest-fang",
    unlockFlag: "ai-flag-floor3-cleared",
    locked: true,
    description: "A vertical floor — more climbing than walking. Rope bridges connect platforms built into a single impossibly tall tree.",
  },
  {
    id: "floor-5",
    index: 5,
    name: "The Drowned Causeway",
    townMapId: "ai-map-town5",
    fieldMapId: "ai-map-field5",
    miniBossEnemyId: "en-causeway-broodmaw",
    floorBossEnemyId: "en-drowned-sovereign",
    uniqueItemId: "ai-item-mistguard-blade",
    unlockFlag: "ai-flag-floor4-cleared",
    locked: true,
    description: "A stone road half-swallowed by a swamp. Mostly underwater, entirely unfriendly to anyone who can't swim in full gear.",
  },
  {
    id: "floor-6",
    index: 6,
    name: "Gilded Quarter",
    townMapId: "ai-map-town6",
    fieldMapId: "ai-map-field6",
    miniBossEnemyId: "en-market-enforcer",
    floorBossEnemyId: "en-golden-magnate",
    uniqueItemId: "ai-item-guild-pendant",
    unlockFlag: "ai-flag-floor5-cleared",
    locked: true,
    description: "The wealthiest floor town yet built — for those who can afford it. Guild politics run this floor more than monsters do.",
  },
  {
    id: "floor-7",
    index: 7,
    name: "Hollow Choir",
    townMapId: "ai-map-town7",
    fieldMapId: "ai-map-field7",
    miniBossEnemyId: "en-choir-conductor",
    floorBossEnemyId: "en-hollow-chorus",
    uniqueItemId: "ai-item-revival-charm",
    unlockFlag: "ai-flag-floor6-cleared",
    locked: true,
    description: "Dead silent. No confirmed field reports agree on why.",
  },
  {
    id: "floor-8",
    index: 8,
    name: "The Iron Maze",
    townMapId: "ai-map-town8",
    fieldMapId: "ai-map-field8",
    miniBossEnemyId: "en-labyrinth-keeper",
    floorBossEnemyId: "en-iron-architect",
    uniqueItemId: "ai-item-gripweave-gloves",
    unlockFlag: "ai-flag-floor7-cleared",
    locked: true,
    description: "A labyrinth floor. Corridors that seem to rearrange themselves — nobody's proven it, and nobody's willing to test it alone.",
  },
  {
    id: "floor-9",
    index: 9,
    name: "Skybreak Terrace",
    townMapId: "ai-map-town9",
    fieldMapId: "ai-map-field9",
    miniBossEnemyId: "en-storm-harrier",
    floorBossEnemyId: "en-skybreak-sentinel",
    uniqueItemId: "ai-item-runners-greaves",
    unlockFlag: "ai-flag-floor8-cleared",
    locked: true,
    description: "High-altitude floor, reportedly visible from Floor 1 on clear days.",
  },
  {
    id: "floor-10",
    index: 10,
    name: "The Tenth Gate",
    townMapId: "ai-map-town10",
    fieldMapId: "ai-map-field10",
    miniBossEnemyId: "en-gate-champion",
    floorBossEnemyId: "en-the-tenth-gatekeeper",
    uniqueItemId: "ai-item-vanguard-greatsword",
    unlockFlag: "ai-flag-floor9-cleared",
    locked: true,
    description: "The first of Aincrad's confirmed 'gate floors' — a milestone boss awaits, and this slice of the climb ends here for now.",
  },
  {
    id: "floor-11",
    index: 11,
    name: "The Sunken Archive",
    townMapId: "ai-map-town11",
    fieldMapId: "ai-map-field11",
    miniBossEnemyId: "en-drowned-cataloguer",
    floorBossEnemyId: "en-archive-warden",
    uniqueItemId: "ai-item-archivists-lens",
    unlockFlag: "ai-flag-floor10-cleared",
    locked: true,
    description: "A library that flooded before anyone could finish cataloguing it. Half the shelves are still legible, if you can hold your breath long enough.",
  },
  {
    id: "floor-12",
    index: 12,
    name: "Ember Foundry",
    townMapId: "ai-map-town12",
    fieldMapId: "ai-map-field12",
    miniBossEnemyId: "en-slag-brute",
    floorBossEnemyId: "en-foundry-heart",
    uniqueItemId: "ai-item-foundry-gauntlets",
    unlockFlag: "ai-flag-floor11-cleared",
    locked: true,
    description: "An industrial floor built around a forge that's never gone cold. Every player who's tried to shut it down has failed a different way.",
  },
  {
    id: "floor-13",
    index: 13,
    name: "Glasswind Reach",
    townMapId: "ai-map-town13",
    fieldMapId: "ai-map-field13",
    miniBossEnemyId: "en-glass-serpent",
    floorBossEnemyId: "en-wind-cut-colossus",
    uniqueItemId: "ai-item-glasswind-cloak",
    unlockFlag: "ai-flag-floor12-cleared",
    locked: true,
    description: "A desert of wind-carved glass. Beautiful, and every surface is sharp enough to draw blood on contact.",
  },
  {
    id: "floor-14",
    index: 14,
    name: "The Hanging Gardens",
    townMapId: "ai-map-town14",
    fieldMapId: "ai-map-field14",
    miniBossEnemyId: "en-thornback-matriarch",
    floorBossEnemyId: "en-garden-sovereign",
    uniqueItemId: "ai-item-bloomguard-charm",
    unlockFlag: "ai-flag-floor13-cleared",
    locked: true,
    description: "Terraced gardens suspended over open air by roots nobody's ever traced to solid ground. Gorgeous. Not remotely safe.",
  },
  {
    id: "floor-15",
    index: 15,
    name: "Duskmarch",
    townMapId: "ai-map-town15",
    fieldMapId: "ai-map-field15",
    miniBossEnemyId: "en-grave-captain",
    floorBossEnemyId: "en-duskmarch-sovereign",
    uniqueItemId: "ai-item-duskmarch-banner",
    unlockFlag: "ai-flag-floor14-cleared",
    locked: true,
    description: "A floor that never fully brightens or fully darkens. The second confirmed milestone floor — the fifteenth gate, some call it.",
  },
  {
    id: "floor-16",
    index: 16,
    name: "Ironclad Docks",
    townMapId: "ai-map-town16",
    fieldMapId: "ai-map-field16",
    miniBossEnemyId: "en-harbor-brute",
    floorBossEnemyId: "en-dreadnought-hull",
    uniqueItemId: "ai-item-dockhand-rig",
    unlockFlag: "ai-flag-floor15-cleared",
    locked: true,
    description: "A harbor floor built for ships that never sail anywhere, guarding a dry-docked hull nobody's supposed to still be inside of.",
  },
  {
    id: "floor-17",
    index: 17,
    name: "The Silent Orchard",
    townMapId: "ai-map-town17",
    fieldMapId: "ai-map-field17",
    miniBossEnemyId: "en-orchard-warden",
    floorBossEnemyId: "en-the-withered-root",
    uniqueItemId: "ai-item-orchard-sickle",
    unlockFlag: "ai-flag-floor16-cleared",
    locked: true,
    description: "Rows of blossoming trees that make no sound at all — not from wind, not from footsteps, not from anything.",
  },
  {
    id: "floor-18",
    index: 18,
    name: "Stormwatch Bastion",
    townMapId: "ai-map-town18",
    fieldMapId: "ai-map-field18",
    miniBossEnemyId: "en-bastion-lieutenant",
    floorBossEnemyId: "en-stormwatch-warlord",
    uniqueItemId: "ai-item-stormwatch-plate",
    unlockFlag: "ai-flag-floor17-cleared",
    locked: true,
    description: "A fortress floor perpetually mid-siege by a storm that never actually breaks. The garrison's been ready for a hundred years of game-time.",
  },
  {
    id: "floor-19",
    index: 19,
    name: "The Withering Court",
    townMapId: "ai-map-town19",
    fieldMapId: "ai-map-field19",
    miniBossEnemyId: "en-court-enforcer",
    floorBossEnemyId: "en-the-faded-monarch",
    uniqueItemId: "ai-item-courtiers-signet",
    unlockFlag: "ai-flag-floor18-cleared",
    locked: true,
    description: "A palace floor built for a royal court that never had any actual subjects. One floor from the next confirmed gate.",
  },
  {
    id: "floor-20",
    index: 20,
    name: "The Twentieth Spire",
    townMapId: "ai-map-town20",
    fieldMapId: "ai-map-field20",
    miniBossEnemyId: "en-spire-vanguard",
    floorBossEnemyId: "en-the-twentieth-warden",
    uniqueItemId: "ai-item-spirebreaker-emblem",
    unlockFlag: "ai-flag-floor19-cleared",
    locked: true,
    description: "The third confirmed milestone floor. From its peak, on a clear day, you can see farther up Aincrad than anyone's ever confirmed reaching.",
  },
];
