import type { FloorDefinitionInput } from "@/types";

export const aincradFloors: FloorDefinitionInput[] = [
  {
    id: "floor-1",
    index: 1,
    name: "Sylvan Threshold",
    townMapId: "ai-map-town1",
    fieldMapId: "ai-map-field1",
    dungeonMapId: "ai-map-dungeon1",
    miniBossEnemyId: "en-alpha-timberwolf",
    floorBossEnemyId: "en-sylvan-guardian",
    uniqueItemId: "ai-item-floor1-unique",
    locked: false,
    description: "A forested first floor built to look survivable. Most of it even is.",
  },
  {
    id: "floor-2",
    index: 2,
    name: "Mistfallen Reach",
    townMapId: "ai-map-town2",
    fieldMapId: "ai-map-field2",
    dungeonMapId: "ai-map-dungeon2",
    miniBossEnemyId: "en-frostfang-alpha",
    floorBossEnemyId: "en-mistfallen-warden",
    uniqueItemId: "ai-item-mistguard-blade",
    unlockFlag: "ai-flag-floor1-cleared",
    locked: true,
    description: "Cold highlands wrapped in permanent fog. Fewer players make it this far.",
  },
  {
    id: "floor-3",
    index: 3,
    name: "Ashen Hollow",
    townMapId: "ai-map-town3",
    fieldMapId: "ai-map-field3",
    dungeonMapId: "ai-map-dungeon3",
    miniBossEnemyId: "en-molten-sentinel",
    floorBossEnemyId: "en-ashen-hollow-king",
    uniqueItemId: "ai-item-floorguard-mail",
    unlockFlag: "ai-flag-floor2-cleared",
    locked: true,
    description: "Volcanic rock and old grief. Someone still keeps a vigil at its dungeon gate.",
  },
  {
    id: "floor-4",
    index: 4,
    name: "Verdant Spire",
    townMapId: "ai-map-town4",
    fieldMapId: "ai-map-field4",
    miniBossEnemyId: "en-spire-ape",
    floorBossEnemyId: "en-verdant-warden",
    uniqueItemId: "ai-item-forest-fang",
    unlockFlag: "ai-flag-floor3-cleared",
    locked: true,
    description: "A vertical floor — more climbing than walking. Rope bridges connect platforms built into a single impossibly tall tree.",
  },
  {
    id: "floor-5",
    index: 5,
    name: "The Drowned Causeway",
    townMapId: "ai-map-town5",
    fieldMapId: "ai-map-field5",
    miniBossEnemyId: "en-causeway-broodmaw",
    floorBossEnemyId: "en-drowned-sovereign",
    uniqueItemId: "ai-item-mistguard-blade",
    unlockFlag: "ai-flag-floor4-cleared",
    locked: true,
    description: "A stone road half-swallowed by a swamp. Mostly underwater, entirely unfriendly to anyone who can't swim in full gear.",
  },
  {
    id: "floor-6",
    index: 6,
    name: "Gilded Quarter",
    townMapId: "ai-map-town6",
    fieldMapId: "ai-map-field6",
    miniBossEnemyId: "en-market-enforcer",
    floorBossEnemyId: "en-golden-magnate",
    uniqueItemId: "ai-item-guild-pendant",
    unlockFlag: "ai-flag-floor5-cleared",
    locked: true,
    description: "The wealthiest floor town yet built — for those who can afford it. Guild politics run this floor more than monsters do.",
  },
  {
    id: "floor-7",
    index: 7,
    name: "Hollow Choir",
    townMapId: "ai-map-town7",
    fieldMapId: "ai-map-field7",
    miniBossEnemyId: "en-choir-conductor",
    floorBossEnemyId: "en-hollow-chorus",
    uniqueItemId: "ai-item-revival-charm",
    unlockFlag: "ai-flag-floor6-cleared",
    locked: true,
    description: "Dead silent. No confirmed field reports agree on why.",
  },
  {
    id: "floor-8",
    index: 8,
    name: "The Iron Maze",
    townMapId: "ai-map-town8",
    fieldMapId: "ai-map-field8",
    miniBossEnemyId: "en-labyrinth-keeper",
    floorBossEnemyId: "en-iron-architect",
    uniqueItemId: "ai-item-gripweave-gloves",
    unlockFlag: "ai-flag-floor7-cleared",
    locked: true,
    description: "A labyrinth floor. Corridors that seem to rearrange themselves — nobody's proven it, and nobody's willing to test it alone.",
  },
  {
    id: "floor-9",
    index: 9,
    name: "Skybreak Terrace",
    townMapId: "ai-map-town9",
    fieldMapId: "ai-map-field9",
    miniBossEnemyId: "en-storm-harrier",
    floorBossEnemyId: "en-skybreak-sentinel",
    uniqueItemId: "ai-item-runners-greaves",
    unlockFlag: "ai-flag-floor8-cleared",
    locked: true,
    description: "High-altitude floor, reportedly visible from Floor 1 on clear days.",
  },
  {
    id: "floor-10",
    index: 10,
    name: "The Tenth Gate",
    townMapId: "ai-map-town10",
    fieldMapId: "ai-map-field10",
    miniBossEnemyId: "en-gate-champion",
    floorBossEnemyId: "en-the-tenth-gatekeeper",
    uniqueItemId: "ai-item-vanguard-greatsword",
    unlockFlag: "ai-flag-floor9-cleared",
    locked: true,
    description: "The first of Aincrad's confirmed 'gate floors' — a milestone boss awaits, and this slice of the climb ends here for now.",
  },
];
