import type { FloorDefinitionInput } from "@/types";

export const aincradFloors: FloorDefinitionInput[] = [
  {
    id: "floor-1",
    index: 1,
    name: "Sylvan Threshold",
    townMapId: "ai-map-town1",
    fieldMapId: "ai-map-field1",
    dungeonMapId: "ai-map-dungeon1",
    miniBossEnemyId: "en-alpha-timberwolf",
    floorBossEnemyId: "en-sylvan-guardian",
    uniqueItemId: "ai-item-floor1-unique",
    locked: false,
    description: "A forested first floor built to look survivable. Most of it even is.",
  },
  {
    id: "floor-2",
    index: 2,
    name: "Mistfallen Reach",
    townMapId: "ai-map-town2",
    fieldMapId: "ai-map-field2",
    dungeonMapId: "ai-map-dungeon2",
    miniBossEnemyId: "en-frostfang-alpha",
    floorBossEnemyId: "en-mistfallen-warden",
    uniqueItemId: "ai-item-mistguard-blade",
    unlockFlag: "ai-flag-floor1-cleared",
    locked: true,
    description: "Cold highlands wrapped in permanent fog. Fewer players make it this far.",
  },
  {
    id: "floor-3",
    index: 3,
    name: "Ashen Hollow",
    townMapId: "ai-map-town3",
    fieldMapId: "ai-map-field3",
    dungeonMapId: "ai-map-dungeon3",
    miniBossEnemyId: "en-molten-sentinel",
    floorBossEnemyId: "en-ashen-hollow-king",
    uniqueItemId: "ai-item-floorguard-mail",
    unlockFlag: "ai-flag-floor2-cleared",
    locked: true,
    description: "Volcanic rock and old grief. Someone still keeps a vigil at its dungeon gate.",
  },
  {
    id: "floor-4",
    index: 4,
    name: "Verdant Spire",
    unlockFlag: "ai-flag-floor3-cleared",
    locked: true,
    description: "Locked. Rumored to be a vertical floor — more climbing than walking.",
  },
  {
    id: "floor-5",
    index: 5,
    name: "The Drowned Causeway",
    locked: true,
    description: "Locked. Scouting reports describe a floor that's mostly underwater.",
  },
  {
    id: "floor-6",
    index: 6,
    name: "Gilded Quarter",
    locked: true,
    description: "Locked. Said to be the wealthiest floor town yet built — for those who can afford it.",
  },
  {
    id: "floor-7",
    index: 7,
    name: "Hollow Choir",
    locked: true,
    description: "Locked. No confirmed reports. Some players claim it's silent. Others claim the opposite.",
  },
  {
    id: "floor-8",
    index: 8,
    name: "The Iron Maze",
    locked: true,
    description: "Locked. A labyrinth floor — no field, no town, just corridors.",
  },
  {
    id: "floor-9",
    index: 9,
    name: "Skybreak Terrace",
    locked: true,
    description: "Locked. High-altitude floor, reportedly visible from Floor 1 on clear days.",
  },
  {
    id: "floor-10",
    index: 10,
    name: "The Tenth Gate",
    locked: true,
    description: "Locked. The first of Aincrad's confirmed 'gate floors' — a milestone boss awaits.",
  },
];
