import type { NpcDefinitionInput } from "@/types";

/**
 * Aincrad — original cast trapped in Floor 1's launch cohort.
 * Original creations inspired only by the general atmosphere of a deadly floating-castle MMO.
 */
export const aincradNpcs: NpcDefinitionInput[] = [
  {
    id: "ai-kirei",
    worldId: "aincrad",
    fullName: "Kirei Sanjo",
    shortName: "Kirei",
    role: "party-member",
    personality: "Blunt, fast-talking beta-tester who's already half a floor ahead of everyone in knowledge.",
    motivation: "Wants to use beta knowledge to keep as many launch players alive as possible.",
    secret: "Froze during the tutorial boss in the beta and let another player die covering for her — she's terrified of freezing again.",
    strength: "Encyclopedic floor knowledge, fast reflexes.",
    weakness: "Overcorrects into recklessness to prove she isn't scared.",
    speechStyle: "Quick, clipped, gamer shorthand.",
    portraitColor: "#2e5a8f",
    portraitGlyph: "zap",
    expressionsAvailable: ["neutral", "smirk", "worried", "shocked", "determined"],
    romanceable: true,
    canJoinParty: true,
    personalQuestId: "ai-q-kirei-freeze",
  },
  {
    id: "ai-toran",
    worldId: "aincrad",
    fullName: "Toran Voss",
    shortName: "Toran",
    role: "mentor",
    personality: "Calm veteran adventurer-type, older than the average player, speaks like he's already made peace with dying here.",
    motivation: "Genuinely believes someone has to hold the line at the front so newer players survive.",
    secret: "Has a terminal-illness diagnosis waiting for him outside — Aincrad might outlast him either way.",
    strength: "Battlefield calm; excellent tactical read on boss patterns.",
    weakness: "Undervalues his own life in group decisions.",
    speechStyle: "Measured, warm, dry humor.",
    portraitColor: "#4a4a4a",
    portraitGlyph: "shield",
    expressionsAvailable: ["neutral", "smile", "determined", "worried"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-toran-legacy",
  },
  {
    id: "ai-mei",
    worldId: "aincrad",
    fullName: "Mei Okuda",
    shortName: "Mei",
    role: "shopkeeper",
    personality: "Cheerful blacksmith who treats crafting like the only sane thing left in the game.",
    motivation: "Refuses to fight; believes she can keep the town alive by keeping its gear alive.",
    secret: "Was a professional welder before login and used a stolen NerveGear slot meant for her brother.",
    strength: "Master crafter; can identify any weapon's hidden potential.",
    weakness: "Guilt-driven; overworks herself to the point of collapse.",
    speechStyle: "Warm, rambling, technical when excited.",
    portraitColor: "#a15c2b",
    portraitGlyph: "hammer",
    expressionsAvailable: ["neutral", "smile", "laugh", "worried", "thinking"],
    romanceable: false,
    canJoinParty: false,
    personalQuestId: "ai-q-mei-brother",
  },
  {
    id: "ai-ryo",
    worldId: "aincrad",
    fullName: "Ryo Katsuragi",
    shortName: "Ryo",
    role: "rival",
    personality: "Guild leader of the Iron Vanguard, competitive, believes strength should decide leadership.",
    motivation: "Wants the Vanguard to be the guild remembered for clearing Aincrad, whatever the cost.",
    secret: "Inflates the Vanguard's boss-clear contributions in public logs to recruit faster.",
    strength: "Charismatic leadership, genuinely skilled fighter.",
    weakness: "Can't handle being publicly wrong.",
    speechStyle: "Loud, commanding, performative.",
    portraitColor: "#8f2e2e",
    portraitGlyph: "flag",
    expressionsAvailable: ["neutral", "smile", "smirk", "angry", "shocked"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-nell",
    worldId: "aincrad",
    fullName: "Nell Farrow",
    shortName: "Nell",
    role: "guild-member",
    personality: "Quiet healer-support type, leader of the small Hearthlight guild.",
    motivation: "Building a guild that prioritizes not losing anyone over clearing fast.",
    secret: "Turned away a desperate solo player who died a day later; she keeps a private list of names because of it.",
    strength: "Support magic, reading party morale.",
    weakness: "Says yes to too many people at once and burns out.",
    speechStyle: "Soft, careful, direct when it matters.",
    portraitColor: "#5b8f6f",
    portraitGlyph: "leaf",
    expressionsAvailable: ["neutral", "smile", "worried", "sad", "determined"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-dask",
    worldId: "aincrad",
    fullName: "Dask Orrin",
    shortName: "Dask",
    role: "guild-member",
    personality: "Gruff leader of the Stonebreakers, prioritizes economic survival over combat glory.",
    motivation: "Believes Aincrad will be survived by whoever controls its markets, not its monsters.",
    secret: "Buys information from players about upcoming floor drops, then corners the market before prices adjust.",
    strength: "Resource logistics; keeps his guild well-supplied.",
    weakness: "Undervalues combat risk; sends undertrained members on supply runs.",
    speechStyle: "Terse, transactional.",
    portraitColor: "#6b6b3d",
    portraitGlyph: "package",
    expressionsAvailable: ["neutral", "smirk", "cold", "frown"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-hollow",
    worldId: "aincrad",
    fullName: "\"Hollow\"",
    shortName: "Hollow",
    role: "neutral",
    personality: "Solo player, avoids parties entirely, real name unknown even to the town.",
    motivation: "Believes attachments are what get people killed in Aincrad.",
    secret: "Was the last surviving member of a five-person party wiped on Floor 1's field on launch day.",
    strength: "Self-sufficient survival skill, excellent scout.",
    weakness: "Physically incapable of asking for help even when dying.",
    speechStyle: "Minimal, flat, occasionally unsettling.",
    portraitColor: "#1c1c1c",
    portraitGlyph: "user-x",
    expressionsAvailable: ["neutral", "cold", "worried", "determined"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-hollow-past",
  },
  {
    id: "ai-arch",
    worldId: "aincrad",
    fullName: "Archivist (System)",
    shortName: "Archivist",
    role: "authority",
    personality: "A strange NPC merchant who seems to know more about the game's rules than any player should.",
    motivation: "Unknown. Sells suspiciously perfect information at suspiciously fair prices.",
    secret: "May not be a standard NPC at all — some players believe the Archivist is a person hiding inside the system.",
    strength: "Perfect knowledge of Aincrad's mechanics.",
    weakness: "Bound by rules it won't explain, and can't act outside them.",
    speechStyle: "Formal, riddling, unnervingly precise.",
    portraitColor: "#3d2b5b",
    portraitGlyph: "sparkles",
    expressionsAvailable: ["neutral", "smile", "thinking"],
    romanceable: false,
    canJoinParty: false,
    codexUnlockedByDefault: true,
  },
];
