import type { NpcDefinitionInput } from "@/types";

/**
 * Aincrad — original cast trapped in Floor 1's launch cohort.
 * Original creations inspired only by the general atmosphere of a deadly floating-castle MMO.
 */
export const aincradNpcs: NpcDefinitionInput[] = [
  {
    id: "ai-kirei",
    worldId: "aincrad",
    fullName: "Kirei Sanjo",
    shortName: "Kirei",
    role: "party-member",
    personality: "Blunt, fast-talking beta-tester who's already half a floor ahead of everyone in knowledge.",
    motivation: "Wants to use beta knowledge to keep as many launch players alive as possible.",
    secret: "Froze during the tutorial boss in the beta and let another player die covering for her — she's terrified of freezing again.",
    strength: "Encyclopedic floor knowledge, fast reflexes.",
    weakness: "Overcorrects into recklessness to prove she isn't scared.",
    speechStyle: "Quick, clipped, gamer shorthand.",
    portraitColor: "#2e5a8f",
    portraitGlyph: "zap",
    expressionsAvailable: ["neutral", "smirk", "worried", "shocked", "determined"],
    romanceable: true,
    canJoinParty: true,
    personalQuestId: "ai-q-kirei-freeze",
  },
  {
    id: "ai-toran",
    worldId: "aincrad",
    fullName: "Toran Voss",
    shortName: "Toran",
    role: "mentor",
    personality: "Calm veteran adventurer-type, older than the average player, speaks like he's already made peace with dying here.",
    motivation: "Genuinely believes someone has to hold the line at the front so newer players survive.",
    secret: "Has a terminal-illness diagnosis waiting for him outside — Aincrad might outlast him either way.",
    strength: "Battlefield calm; excellent tactical read on boss patterns.",
    weakness: "Undervalues his own life in group decisions.",
    speechStyle: "Measured, warm, dry humor.",
    portraitColor: "#4a4a4a",
    portraitGlyph: "shield",
    expressionsAvailable: ["neutral", "smile", "determined", "worried"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-toran-legacy",
  },
  {
    id: "ai-mei",
    worldId: "aincrad",
    fullName: "Mei Okuda",
    shortName: "Mei",
    role: "shopkeeper",
    personality: "Cheerful blacksmith who treats crafting like the only sane thing left in the game.",
    motivation: "Refuses to fight; believes she can keep the town alive by keeping its gear alive.",
    secret: "Was a professional welder before login and used a stolen NerveGear slot meant for her brother.",
    strength: "Master crafter; can identify any weapon's hidden potential.",
    weakness: "Guilt-driven; overworks herself to the point of collapse.",
    speechStyle: "Warm, rambling, technical when excited.",
    portraitColor: "#a15c2b",
    portraitGlyph: "hammer",
    expressionsAvailable: ["neutral", "smile", "laugh", "worried", "thinking"],
    romanceable: false,
    canJoinParty: false,
    personalQuestId: "ai-q-mei-brother",
  },
  {
    id: "ai-ryo",
    worldId: "aincrad",
    fullName: "Ryo Katsuragi",
    shortName: "Ryo",
    role: "rival",
    personality: "Guild leader of the Iron Vanguard, competitive, believes strength should decide leadership.",
    motivation: "Wants the Vanguard to be the guild remembered for clearing Aincrad, whatever the cost.",
    secret: "Inflates the Vanguard's boss-clear contributions in public logs to recruit faster.",
    strength: "Charismatic leadership, genuinely skilled fighter.",
    weakness: "Can't handle being publicly wrong.",
    speechStyle: "Loud, commanding, performative.",
    portraitColor: "#8f2e2e",
    portraitGlyph: "flag",
    expressionsAvailable: ["neutral", "smile", "smirk", "angry", "shocked"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-nell",
    worldId: "aincrad",
    fullName: "Nell Farrow",
    shortName: "Nell",
    role: "guild-member",
    personality: "Quiet healer-support type, leader of the small Hearthlight guild.",
    motivation: "Building a guild that prioritizes not losing anyone over clearing fast.",
    secret: "Turned away a desperate solo player who died a day later; she keeps a private list of names because of it.",
    strength: "Support magic, reading party morale.",
    weakness: "Says yes to too many people at once and burns out.",
    speechStyle: "Soft, careful, direct when it matters.",
    portraitColor: "#5b8f6f",
    portraitGlyph: "leaf",
    expressionsAvailable: ["neutral", "smile", "worried", "sad", "determined"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-dask",
    worldId: "aincrad",
    fullName: "Dask Orrin",
    shortName: "Dask",
    role: "guild-member",
    personality: "Gruff leader of the Stonebreakers, prioritizes economic survival over combat glory.",
    motivation: "Believes Aincrad will be survived by whoever controls its markets, not its monsters.",
    secret: "Buys information from players about upcoming floor drops, then corners the market before prices adjust.",
    strength: "Resource logistics; keeps his guild well-supplied.",
    weakness: "Undervalues combat risk; sends undertrained members on supply runs.",
    speechStyle: "Terse, transactional.",
    portraitColor: "#6b6b3d",
    portraitGlyph: "package",
    expressionsAvailable: ["neutral", "smirk", "cold", "frown"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-hollow",
    worldId: "aincrad",
    fullName: "\"Hollow\"",
    shortName: "Hollow",
    role: "neutral",
    personality: "Solo player, avoids parties entirely, real name unknown even to the town.",
    motivation: "Believes attachments are what get people killed in Aincrad.",
    secret: "Was the last surviving member of a five-person party wiped on Floor 1's field on launch day.",
    strength: "Self-sufficient survival skill, excellent scout.",
    weakness: "Physically incapable of asking for help even when dying.",
    speechStyle: "Minimal, flat, occasionally unsettling.",
    portraitColor: "#1c1c1c",
    portraitGlyph: "user-x",
    expressionsAvailable: ["neutral", "cold", "worried", "determined"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-hollow-past",
  },
  {
    id: "ai-arch",
    worldId: "aincrad",
    fullName: "Archivist (System)",
    shortName: "Archivist",
    role: "authority",
    personality: "A strange NPC merchant who seems to know more about the game's rules than any player should.",
    motivation: "Unknown. Sells suspiciously perfect information at suspiciously fair prices.",
    secret: "May not be a standard NPC at all — some players believe the Archivist is a person hiding inside the system.",
    strength: "Perfect knowledge of Aincrad's mechanics.",
    weakness: "Bound by rules it won't explain, and can't act outside them.",
    speechStyle: "Formal, riddling, unnervingly precise.",
    portraitColor: "#3d2b5b",
    portraitGlyph: "sparkles",
    expressionsAvailable: ["neutral", "smile", "thinking"],
    romanceable: false,
    canJoinParty: false,
    codexUnlockedByDefault: true,
  },

  /* ------------------------------- Floors 4-10: local cast ------------------------------- */
  {
    id: "ai-sena",
    worldId: "aincrad",
    fullName: "Sena Kurogane",
    shortName: "Sena",
    role: "guild-member",
    personality: "Fearless climber, treats the Spire's rope bridges like solid ground.",
    motivation: "Wants to map every platform of the Spire before anyone else does.",
    secret: "Has fallen from the Spire twice and only survived because a stranger's Guard skill happened to proc in time — she's never found out who.",
    strength: "Vertical traversal, spotting safe routes others miss.",
    weakness: "Underestimates how exhausted her party is after a long climb.",
    speechStyle: "Fast, breathless, always mid-motion.",
    portraitColor: "#4a7a5a",
    portraitGlyph: "mountain-snow",
    expressionsAvailable: ["neutral", "smile", "determined", "shocked"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-bram",
    worldId: "aincrad",
    fullName: "Bram Oyelaran",
    shortName: "Bram",
    role: "shopkeeper",
    personality: "Calm amphibious-gear trader, treats the Causeway's dangers like a Tuesday.",
    motivation: "Believes he can out-fit every player on the floor well enough that nobody drowns on his watch.",
    secret: "Lost his original party to the Causeway on launch week; every discount he gives is quietly a way of making up for it.",
    strength: "Equipment knowledge, unshakeable calm.",
    weakness: "Never talks about what actually happened to his old party.",
    speechStyle: "Slow, deliberate, dry humor.",
    portraitColor: "#2a4a5a",
    portraitGlyph: "anchor",
    expressionsAvailable: ["neutral", "smile", "worried", "cold"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-iris",
    worldId: "aincrad",
    fullName: "Iris Vantille",
    shortName: "Iris",
    role: "rival",
    personality: "Sharp-tongued market broker who treats every conversation as a negotiation.",
    motivation: "Believes the Gilded Quarter's economy is the only stable thing left in Aincrad, and intends to keep it that way.",
    secret: "Manipulates floor drop-rate rumors to move prices in her favor.",
    strength: "Reads people and markets equally well.",
    weakness: "Can't resist a good deal even when it's clearly a trap.",
    speechStyle: "Quick, transactional, faintly amused.",
    portraitColor: "#9a7a20",
    portraitGlyph: "coins",
    expressionsAvailable: ["neutral", "smirk", "smile", "cold"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-choirkeeper",
    worldId: "aincrad",
    fullName: "\"The Choirkeeper\"",
    shortName: "Choirkeeper",
    role: "neutral",
    personality: "Speaks only in whispers, tends a floor nobody else wants to stay on.",
    motivation: "Unknown. Seems to be listening for something specific in the silence.",
    secret: "Was one of the first players to reach Floor 7, and chose to stay rather than continue climbing.",
    strength: "Total familiarity with the Choir floor's patterns.",
    weakness: "Hasn't spoken above a whisper in longer than anyone can verify.",
    speechStyle: "Whispered, fragmentary.",
    portraitColor: "#3a3a5a",
    portraitGlyph: "music",
    expressionsAvailable: ["neutral", "worried", "sad"],
    romanceable: false,
    canJoinParty: false,
    personalQuestId: "ai-q-choirkeeper-past",
  },
  {
    id: "ai-doc-renner",
    worldId: "aincrad",
    fullName: "\"Doc\" Renner",
    shortName: "Doc Renner",
    role: "mentor",
    personality: "Obsessive maze cartographer, treats the Iron Maze like a puzzle worth a lifetime.",
    motivation: "Wants to be the first to draw a complete, accurate map of the maze's shifting layout.",
    secret: "Suspects the maze is rearranged on purpose by something inside it, not randomly — and is quietly right.",
    strength: "Pattern recognition, meticulous notes.",
    weakness: "Will delay a party's progress to update his map instead of retreating.",
    speechStyle: "Rambling, technical, self-interrupting.",
    portraitColor: "#5a5a5a",
    portraitGlyph: "compass",
    expressionsAvailable: ["neutral", "smile", "thinking", "shocked"],
    romanceable: false,
    canJoinParty: true,
  },
  {
    id: "ai-wren",
    worldId: "aincrad",
    fullName: "Wren Castellan",
    shortName: "Wren",
    role: "mentor",
    personality: "Veteran scout, quietly nostalgic about how far the party's come since Floor 1.",
    motivation: "Wants to see the party reach the Tenth Gate more than she wants credit for helping.",
    secret: "Was on Floor 1 the same launch day as the player — she remembers people who didn't make it this far.",
    strength: "Aerial scouting, calm under pressure.",
    weakness: "Holds onto grief for people who didn't survive the early floors.",
    speechStyle: "Warm, plainspoken, occasionally wistful.",
    portraitColor: "#5a7a9a",
    portraitGlyph: "feather",
    expressionsAvailable: ["neutral", "smile", "sad", "determined"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-ilyana",
    worldId: "aincrad",
    fullName: "Ilyana Vasko",
    shortName: "Ilyana",
    role: "rival",
    personality: "Former ally of the Gate Champion, guarded and testing everyone who arrives at Gatewatch.",
    motivation: "Wants to know if the party is strong enough to survive the Tenth Gate, or just one more name for the list of people who didn't.",
    secret: "Was supposed to be part of the first attempt on the Gate — she pulled out at the last minute, and the rest of that party never came back.",
    strength: "Tactical planning, brutal honesty.",
    weakness: "Second-guesses every decision because of the one time she didn't.",
    speechStyle: "Clipped, direct, no patience for false confidence.",
    portraitColor: "#6a5a4a",
    portraitGlyph: "flag",
    expressionsAvailable: ["neutral", "cold", "worried", "determined"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-ilyana-guilt",
  },
];
