import type { NpcDefinitionInput } from "@/types";

/**
 * Aincrad — original cast trapped in Floor 1's launch cohort.
 * Original creations inspired only by the general atmosphere of a deadly floating-castle MMO.
 */
export const aincradNpcs: NpcDefinitionInput[] = [
  {
    id: "ai-kirei",
    worldId: "aincrad",
    fullName: "Silica",
    shortName: "Silica",
    role: "party-member",
    personality: "Blunt, fast-talking beta-tester who's already half a floor ahead of everyone in knowledge.",
    motivation: "Wants to use beta knowledge to keep as many launch players alive as possible.",
    secret: "Froze during the tutorial boss in the beta and let another player die covering for her — she's terrified of freezing again.",
    strength: "Encyclopedic floor knowledge, fast reflexes.",
    weakness: "Overcorrects into recklessness to prove she isn't scared.",
    speechStyle: "Quick, clipped, gamer shorthand.",
    portraitColor: "#2e5a8f",
    portraitGlyph: "zap",
    hairColor: "black",
    hairstyle: "ponytail",
    eyeColor: "dark-brown",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smirk", "worried", "shocked", "determined"],
    romanceable: true,
    canJoinParty: true,
    personalQuestId: "ai-q-kirei-freeze",
  },
  {
    id: "ai-toran",
    worldId: "aincrad",
    fullName: "Klein",
    shortName: "Klein",
    role: "mentor",
    personality: "Calm veteran adventurer-type, older than the average player, speaks like he's already made peace with dying here.",
    motivation: "Genuinely believes someone has to hold the line at the front so newer players survive.",
    secret: "Has a terminal-illness diagnosis waiting for him outside — Aincrad might outlast him either way.",
    strength: "Battlefield calm; excellent tactical read on boss patterns.",
    weakness: "Undervalues his own life in group decisions.",
    speechStyle: "Measured, warm, dry humor.",
    portraitColor: "#4a4a4a",
    portraitGlyph: "shield",
    hairColor: "silver",
    hairstyle: "short",
    eyeColor: "gray",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smile", "determined", "worried"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-toran-legacy",
  },
  {
    id: "ai-mei",
    worldId: "aincrad",
    fullName: "Lisbeth",
    shortName: "Lisbeth",
    role: "shopkeeper",
    personality: "Cheerful blacksmith who treats crafting like the only sane thing left in the game.",
    motivation: "Refuses to fight; believes she can keep the town alive by keeping its gear alive.",
    secret: "Was a professional welder before login and used a stolen NerveGear slot meant for her brother.",
    strength: "Master crafter; can identify any weapon's hidden potential.",
    weakness: "Guilt-driven; overworks herself to the point of collapse.",
    speechStyle: "Warm, rambling, technical when excited.",
    portraitColor: "#a15c2b",
    portraitGlyph: "hammer",
    hairColor: "brown",
    hairstyle: "braided",
    eyeColor: "hazel",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smile", "laugh", "worried", "thinking"],
    romanceable: false,
    canJoinParty: false,
    personalQuestId: "ai-q-mei-brother",
  },
  {
    id: "ai-ryo",
    worldId: "aincrad",
    fullName: "Kibaou",
    shortName: "Kibaou",
    role: "rival",
    personality: "Guild leader of the Iron Vanguard, competitive, believes strength should decide leadership.",
    motivation: "Wants the Vanguard to be the guild remembered for clearing Aincrad, whatever the cost.",
    secret: "Inflates the Vanguard's boss-clear contributions in public logs to recruit faster.",
    strength: "Charismatic leadership, genuinely skilled fighter.",
    weakness: "Can't handle being publicly wrong.",
    speechStyle: "Loud, commanding, performative.",
    portraitColor: "#8f2e2e",
    portraitGlyph: "flag",
    hairColor: "auburn",
    hairstyle: "short",
    eyeColor: "amber",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smile", "smirk", "angry", "shocked"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-nell",
    worldId: "aincrad",
    fullName: "Sachi",
    shortName: "Sachi",
    role: "guild-member",
    personality: "Quiet healer-support type, leader of the small Hearthlight guild.",
    motivation: "Building a guild that prioritizes not losing anyone over clearing fast.",
    secret: "Turned away a desperate solo player who died a day later; she keeps a private list of names because of it.",
    strength: "Support magic, reading party morale.",
    weakness: "Says yes to too many people at once and burns out.",
    speechStyle: "Soft, careful, direct when it matters.",
    portraitColor: "#5b8f6f",
    portraitGlyph: "leaf",
    hairColor: "ash-blonde",
    hairstyle: "long",
    eyeColor: "steel-blue",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "smile", "worried", "sad", "determined"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-dask",
    worldId: "aincrad",
    fullName: "Agil",
    shortName: "Agil",
    role: "guild-member",
    personality: "Gruff leader of the Stonebreakers, prioritizes economic survival over combat glory.",
    motivation: "Believes Aincrad will be survived by whoever controls its markets, not its monsters.",
    secret: "Buys information from players about upcoming floor drops, then corners the market before prices adjust.",
    strength: "Resource logistics; keeps his guild well-supplied.",
    weakness: "Undervalues combat risk; sends undertrained members on supply runs.",
    speechStyle: "Terse, transactional.",
    portraitColor: "#6b6b3d",
    portraitGlyph: "package",
    hairColor: "charcoal",
    hairstyle: "buzzcut",
    eyeColor: "onyx",
    skinTone: "olive",
    expressionsAvailable: ["neutral", "smirk", "cold", "frown"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-hollow",
    worldId: "aincrad",
    fullName: "\"Yuuki\"",
    shortName: "Yuuki",
    role: "neutral",
    personality: "Solo player, avoids parties entirely, real name unknown even to the town.",
    motivation: "Believes attachments are what get people killed in Aincrad.",
    secret: "Was the last surviving member of a five-person party wiped on Floor 1's field on launch day.",
    strength: "Self-sufficient survival skill, excellent scout.",
    weakness: "Physically incapable of asking for help even when dying.",
    speechStyle: "Minimal, flat, occasionally unsettling.",
    portraitColor: "#1c1c1c",
    portraitGlyph: "user-x",
    hairColor: "black",
    hairstyle: "short",
    eyeColor: "onyx",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "cold", "worried", "determined"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-hollow-past",
  },
  {
    id: "ai-arch",
    worldId: "aincrad",
    fullName: "Yui (System)",
    shortName: "Yui",
    role: "authority",
    personality: "A strange NPC merchant who seems to know more about the game's rules than any player should.",
    motivation: "Unknown. Sells suspiciously perfect information at suspiciously fair prices.",
    secret: "May not be a standard NPC at all — some players believe Yui is a person hiding inside the system.",
    strength: "Perfect knowledge of Aincrad's mechanics.",
    weakness: "Bound by rules it won't explain, and can't act outside them.",
    speechStyle: "Formal, riddling, unnervingly precise.",
    portraitColor: "#3d2b5b",
    portraitGlyph: "sparkles",
    hairColor: "silver",
    hairstyle: "long",
    eyeColor: "amber",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "smile", "thinking"],
    romanceable: false,
    canJoinParty: false,
    codexUnlockedByDefault: true,
  },

  /* ------------------------------- Floors 4-10: local cast ------------------------------- */
  {
    id: "ai-sena",
    worldId: "aincrad",
    fullName: "Sena Kurogane",
    shortName: "Sena",
    role: "guild-member",
    personality: "Fearless climber, treats the Spire's rope bridges like solid ground.",
    motivation: "Wants to map every platform of the Spire before anyone else does.",
    secret: "Has fallen from the Spire twice and only survived because a stranger's Guard skill happened to proc in time — she's never found out who.",
    strength: "Vertical traversal, spotting safe routes others miss.",
    weakness: "Underestimates how exhausted her party is after a long climb.",
    speechStyle: "Fast, breathless, always mid-motion.",
    portraitColor: "#4a7a5a",
    portraitGlyph: "mountain-snow",
    hairColor: "brown",
    hairstyle: "ponytail",
    eyeColor: "hazel",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smile", "determined", "shocked"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-bram",
    worldId: "aincrad",
    fullName: "Bram Oyelaran",
    shortName: "Bram",
    role: "shopkeeper",
    personality: "Calm amphibious-gear trader, treats the Causeway's dangers like a Tuesday.",
    motivation: "Believes he can out-fit every player on the floor well enough that nobody drowns on his watch.",
    secret: "Lost his original party to the Causeway on launch week; every discount he gives is quietly a way of making up for it.",
    strength: "Equipment knowledge, unshakeable calm.",
    weakness: "Never talks about what actually happened to his old party.",
    speechStyle: "Slow, deliberate, dry humor.",
    portraitColor: "#2a4a5a",
    portraitGlyph: "anchor",
    hairColor: "black",
    hairstyle: "short",
    eyeColor: "dark-brown",
    skinTone: "deep",
    expressionsAvailable: ["neutral", "smile", "worried", "cold"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-iris",
    worldId: "aincrad",
    fullName: "Iris Vantille",
    shortName: "Iris",
    role: "rival",
    personality: "Sharp-tongued market broker who treats every conversation as a negotiation.",
    motivation: "Believes the Gilded Quarter's economy is the only stable thing left in Aincrad, and intends to keep it that way.",
    secret: "Manipulates floor drop-rate rumors to move prices in her favor.",
    strength: "Reads people and markets equally well.",
    weakness: "Can't resist a good deal even when it's clearly a trap.",
    speechStyle: "Quick, transactional, faintly amused.",
    portraitColor: "#9a7a20",
    portraitGlyph: "coins",
    hairColor: "auburn",
    hairstyle: "wavy",
    eyeColor: "amber",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smirk", "smile", "cold"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-choirkeeper",
    worldId: "aincrad",
    fullName: "\"The Choirkeeper\"",
    shortName: "Choirkeeper",
    role: "neutral",
    personality: "Speaks only in whispers, tends a floor nobody else wants to stay on.",
    motivation: "Unknown. Seems to be listening for something specific in the silence.",
    secret: "Was one of the first players to reach Floor 7, and chose to stay rather than continue climbing.",
    strength: "Total familiarity with the Choir floor's patterns.",
    weakness: "Hasn't spoken above a whisper in longer than anyone can verify.",
    speechStyle: "Whispered, fragmentary.",
    portraitColor: "#3a3a5a",
    portraitGlyph: "music",
    hairColor: "silver",
    hairstyle: "long",
    eyeColor: "gray",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "worried", "sad"],
    romanceable: false,
    canJoinParty: false,
    personalQuestId: "ai-q-choirkeeper-past",
  },
  {
    id: "ai-doc-renner",
    worldId: "aincrad",
    fullName: "\"Doc\" Renner",
    shortName: "Doc Renner",
    role: "mentor",
    personality: "Obsessive maze cartographer, treats the Iron Maze like a puzzle worth a lifetime.",
    motivation: "Wants to be the first to draw a complete, accurate map of the maze's shifting layout.",
    secret: "Suspects the maze is rearranged on purpose by something inside it, not randomly — and is quietly right.",
    strength: "Pattern recognition, meticulous notes.",
    weakness: "Will delay a party's progress to update his map instead of retreating.",
    speechStyle: "Rambling, technical, self-interrupting.",
    portraitColor: "#5a5a5a",
    portraitGlyph: "compass",
    hairColor: "brown",
    hairstyle: "short",
    eyeColor: "hazel",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smile", "thinking", "shocked"],
    romanceable: false,
    canJoinParty: true,
  },
  {
    id: "ai-wren",
    worldId: "aincrad",
    fullName: "Wren Castellan",
    shortName: "Wren",
    role: "mentor",
    personality: "Veteran scout, quietly nostalgic about how far the party's come since Floor 1.",
    motivation: "Wants to see the party reach the Tenth Gate more than she wants credit for helping.",
    secret: "Was on Floor 1 the same launch day as the player — she remembers people who didn't make it this far.",
    strength: "Aerial scouting, calm under pressure.",
    weakness: "Holds onto grief for people who didn't survive the early floors.",
    speechStyle: "Warm, plainspoken, occasionally wistful.",
    portraitColor: "#5a7a9a",
    portraitGlyph: "feather",
    hairColor: "ash-blonde",
    hairstyle: "braided",
    eyeColor: "steel-blue",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smile", "sad", "determined"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-ilyana",
    worldId: "aincrad",
    fullName: "Ilyana Vasko",
    shortName: "Ilyana",
    role: "rival",
    personality: "Former ally of the Gate Champion, guarded and testing everyone who arrives at Gatewatch.",
    motivation: "Wants to know if the party is strong enough to survive the Tenth Gate, or just one more name for the list of people who didn't.",
    secret: "Was supposed to be part of the first attempt on the Gate — she pulled out at the last minute, and the rest of that party never came back.",
    strength: "Tactical planning, brutal honesty.",
    weakness: "Second-guesses every decision because of the one time she didn't.",
    speechStyle: "Clipped, direct, no patience for false confidence.",
    portraitColor: "#6a5a4a",
    portraitGlyph: "flag",
    hairColor: "black",
    hairstyle: "short",
    eyeColor: "dark-brown",
    skinTone: "olive",
    expressionsAvailable: ["neutral", "cold", "worried", "determined"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-ilyana-guilt",
  },

  /* ------------------------------- Floors 11-20: local cast ------------------------------- */
  {
    id: "ai-mireille",
    worldId: "aincrad",
    fullName: "Mireille Osten",
    shortName: "Mireille",
    role: "mentor",
    personality: "Methodical archivist, treats the flooded stacks like a puzzle worth drowning for.",
    motivation: "Wants to recover one specific waterlogged text before it dissolves for good.",
    secret: "The text she's chasing is a survivor's account from a guild that was wiped clearing this floor — she knew one of them.",
    strength: "Research, pattern recognition, holds her breath a genuinely unsettling amount of time.",
    weakness: "Risks drowning gear and party alike chasing one more shelf.",
    speechStyle: "Precise, academic, trails off mid-sentence when reading.",
    portraitColor: "#2a5a5a",
    portraitGlyph: "book-marked",
    hairColor: "brown",
    hairstyle: "braided",
    eyeColor: "hazel",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "thinking", "determined", "sad"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-talon",
    worldId: "aincrad",
    fullName: "Talon Vekric",
    shortName: "Talon",
    role: "shopkeeper",
    personality: "Gruff master smith who talks to the foundry like it's listening.",
    motivation: "Believes he can forge something strong enough to finally shut the furnace down for good.",
    secret: "He's the one who accidentally set the furnace to never go cold, on launch week — nobody else knows.",
    strength: "Weaponsmithing, heat tolerance, blunt honesty.",
    weakness: "Guilt keeps him from ever leaving the floor, even to resupply.",
    speechStyle: "Short, gravelly, warms up slowly.",
    portraitColor: "#8a3a1f",
    portraitGlyph: "hammer",
    hairColor: "charcoal",
    hairstyle: "buzzcut",
    eyeColor: "amber",
    skinTone: "deep",
    expressionsAvailable: ["neutral", "cold", "frown", "determined"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-reeve",
    worldId: "aincrad",
    fullName: "Reeve Calantha",
    shortName: "Reeve",
    role: "guild-member",
    personality: "Sharp-eyed glass prospector, reads the dunes like other people read weather.",
    motivation: "Wants to map every safe path through Glasswind Reach before someone bleeds out finding one the hard way.",
    secret: "Has already lost two fingers to the glass and hides it under her gloves.",
    strength: "Terrain reading, improvised glasswork armor repair.",
    weakness: "Refuses to admit when the reach has actually hurt her.",
    speechStyle: "Dry, clipped, occasionally poetic about the scenery.",
    portraitColor: "#6a9a9a",
    portraitGlyph: "gem",
    hairColor: "silver",
    hairstyle: "ponytail",
    eyeColor: "steel-blue",
    skinTone: "light",
    expressionsAvailable: ["neutral", "smirk", "worried", "determined"],
    romanceable: true,
    canJoinParty: true,
  },
  {
    id: "ai-fenna",
    worldId: "aincrad",
    fullName: "Fenna Brightleaf",
    shortName: "Fenna",
    role: "guild-member",
    personality: "Gentle botanist who talks about the Hanging Gardens like they're a living thing worth protecting.",
    motivation: "Believes the gardens are the closest thing left to something actually alive and growing on its own terms.",
    secret: "Has been quietly feeding data on the garden's growth patterns to Doc Renner on Floor 8, convinced the two floors are connected somehow.",
    strength: "Botany, careful footing on unstable ground.",
    weakness: "Puts the garden's safety ahead of her own more than once a week.",
    speechStyle: "Soft, warm, occasionally rambles about root systems.",
    portraitColor: "#3a7a2f",
    portraitGlyph: "flower",
    hairColor: "auburn",
    hairstyle: "wavy",
    eyeColor: "hazel",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "smile", "worried", "thinking"],
    romanceable: true,
    canJoinParty: false,
  },
  {
    id: "ai-corvin",
    worldId: "aincrad",
    fullName: "Corvin Ashe",
    shortName: "Corvin",
    role: "mentor",
    personality: "Quiet grave-keeper of Duskmarch, treats every fallen player's marker like it matters that someone remembers.",
    motivation: "Wants every name lost on this floor properly recorded before Aincrad forgets them too.",
    secret: "Keeps a second, unofficial ledger of names the system itself deleted after certain floor incidents — proof something was scrubbed.",
    strength: "Total knowledge of Duskmarch's terrain and its dead.",
    weakness: "Struggles to focus on the living when there's a name still unrecorded.",
    speechStyle: "Low, measured, unhurried even in danger.",
    portraitColor: "#3a2a5a",
    portraitGlyph: "flag",
    hairColor: "black",
    hairstyle: "long",
    eyeColor: "onyx",
    skinTone: "olive",
    expressionsAvailable: ["neutral", "sad", "determined", "cold"],
    romanceable: false,
    canJoinParty: true,
    personalQuestId: "ai-q-corvin-ledger",
  },
  {
    id: "ai-brogan",
    worldId: "aincrad",
    fullName: "Brogan Steele",
    shortName: "Brogan",
    role: "guild-member",
    personality: "Loud, practical dock foreman who runs the Ironclad Docks like an actual functioning port.",
    motivation: "Believes an organized supply chain will outlast every guild's combat record.",
    secret: "Has been quietly stockpiling gear in case the docks ever need to evacuate a mass casualty event.",
    strength: "Logistics, hauling capacity, morale under pressure.",
    weakness: "Overcommits crews to jobs the docks can't actually staff.",
    speechStyle: "Loud, direct, foreman's cadence.",
    portraitColor: "#5a6a7a",
    portraitGlyph: "anchor",
    hairColor: "brown",
    hairstyle: "short",
    eyeColor: "dark-brown",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smile", "determined", "frown"],
    romanceable: false,
    canJoinParty: false,
  },
  {
    id: "ai-wisteria",
    worldId: "aincrad",
    fullName: "Wisteria Vane",
    shortName: "Wisteria",
    role: "neutral",
    personality: "Speaks only just above a whisper, matches the orchard's silence out of what looks like respect.",
    motivation: "Believes the orchard's silence is protecting something and doesn't want to be the one who breaks it.",
    secret: "Has heard exactly one sound in the orchard in months — her own name, spoken by no one she could find.",
    strength: "Total stealth, reads the orchard's smallest changes.",
    weakness: "So committed to quiet that she waits too long to call for help.",
    speechStyle: "Whispered, gentle, precise.",
    portraitColor: "#4a6a3f",
    portraitGlyph: "flower",
    hairColor: "ash-blonde",
    hairstyle: "long",
    eyeColor: "gray",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "worried", "sad", "thinking"],
    romanceable: true,
    canJoinParty: false,
  },
  {
    id: "ai-draven",
    worldId: "aincrad",
    fullName: "Draven Kestrel",
    shortName: "Draven",
    role: "authority",
    personality: "Stern garrison captain who's held Stormwatch Bastion together through pure stubbornness.",
    motivation: "Refuses to let the bastion fall on his watch, storm or otherwise.",
    secret: "Privately believes the storm will never break and the garrison is holding a line that doesn't need holding — he keeps that to himself for morale's sake.",
    strength: "Command, defensive tactics, unshakeable composure.",
    weakness: "Won't ask for reinforcements even when the garrison badly needs them.",
    speechStyle: "Formal, commanding, clipped.",
    portraitColor: "#3a4a60",
    portraitGlyph: "shield",
    hairColor: "silver",
    hairstyle: "short",
    eyeColor: "steel-blue",
    skinTone: "light",
    expressionsAvailable: ["neutral", "cold", "determined", "angry"],
    romanceable: false,
    canJoinParty: true,
  },
  {
    id: "ai-isolde",
    worldId: "aincrad",
    fullName: "Isolde Thorne",
    shortName: "Isolde",
    role: "neutral",
    personality: "Faded-court historian who talks about the Withering Court's fictional royalty like real people she personally failed.",
    motivation: "Wants to finish a complete history of a court that never actually existed before login, for reasons she won't explain.",
    secret: "The 'history' she's writing is actually about her own guild, renamed and re-costumed — the court's fall mirrors exactly how her guild fell apart.",
    strength: "Storytelling, reading people's unspoken grief.",
    weakness: "Won't admit the court story is really about her.",
    speechStyle: "Formal, theatrical, slips into first person by accident.",
    portraitColor: "#4a3a5a",
    portraitGlyph: "scroll",
    hairColor: "auburn",
    hairstyle: "twintails",
    eyeColor: "amber",
    skinTone: "porcelain",
    expressionsAvailable: ["neutral", "sad", "smirk", "thinking"],
    romanceable: true,
    canJoinParty: false,
  },
  {
    id: "ai-renn",
    worldId: "aincrad",
    fullName: "Renn Aurelio",
    shortName: "Renn",
    role: "rival",
    personality: "Veteran climber, competitive but genuinely relieved every time someone new catches up to the front line.",
    motivation: "Wants to reach the top of Aincrad specifically to prove the climb was survivable, not just possible.",
    secret: "Has attempted the Twentieth Spire's boss alone twice already and lost both times — doesn't want anyone to know how close it came to being three.",
    strength: "Raw front-line combat experience, unmatched floor knowledge past Floor 15.",
    weakness: "Pride keeps her attempting alone what she should ask for help with.",
    speechStyle: "Confident, warm, competitive without being cruel about it.",
    portraitColor: "#4a4a7a",
    portraitGlyph: "sword",
    hairColor: "black",
    hairstyle: "ponytail",
    eyeColor: "steel-blue",
    skinTone: "tan",
    expressionsAvailable: ["neutral", "smirk", "determined", "shocked"],
    romanceable: true,
    canJoinParty: true,
    personalQuestId: "ai-q-renn-pride",
  },
];
