import type { QuestDefinitionInput } from "@/types";

export const aincradQuests: QuestDefinitionInput[] = [
  {
    id: "ai-q-main-locked-sky",
    worldId: "aincrad",
    title: "The Locked Sky",
    type: "main",
    description: "Logout is gone. The only way out of Aincrad is through all one hundred floors — starting with the first.",
    objectives: [
      { id: "learn-no-logout", text: "Understand what's actually happened." },
      { id: "choose-alone-or-together", text: "Decide whether to stay solo or find people to fight alongside." },
      { id: "complete-training", text: "Complete a training quest in the Town of Beginnings." },
      { id: "explore-field", text: "Explore the Floor 1 field." },
      { id: "clear-dungeon", text: "Clear the Floor 1 dungeon." },
      { id: "raid-boss", text: "Take part in the Floor 1 boss raid." },
    ],
    rewardSummary: "Determines who survives the first boss raid and how Floor 1's community remembers you.",
  },
  {
    id: "ai-q-kirei-freeze",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-kirei",
    title: "The Beta Tester's Ghost",
    description: "Silica knows this floor better than anyone alive — and is quietly terrified of freezing up again like she did in the beta.",
    objectives: [
      { id: "learn-secret", text: "Learn what happened to Silica during the beta." },
      { id: "support-or-not", text: "Decide how to handle it when it happens again." },
    ],
    rewardSummary: "Shapes whether Silica trusts herself in the boss raid.",
  },
  {
    id: "ai-q-toran-legacy",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-toran",
    title: "What Klein Leaves Behind",
    description: "Klein talks about Aincrad like a man who has already made peace with not going home.",
    objectives: [
      { id: "learn-condition", text: "Learn why Klein isn't afraid of dying here." },
      { id: "decide-role", text: "Decide what role he plays in the boss raid." },
    ],
    rewardSummary: "Affects Klein's survival odds in the raid and what he says if he doesn't make it.",
  },
  {
    id: "ai-q-mei-brother",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-mei",
    title: "The Slot That Wasn't Hers",
    description: "Lisbeth took her brother's NerveGear slot. She hasn't said why, and she flinches when anyone asks.",
    objectives: [
      { id: "earn-trust", text: "Earn enough trust for Lisbeth to explain." },
      { id: "respond", text: "Decide how to respond to what she tells you." },
    ],
    hidden: true,
    rewardSummary: "Unlocks Lisbeth's best crafting recipes if handled with care.",
  },
  {
    id: "ai-q-hollow-past",
    worldId: "aincrad",
    type: "hidden",
    hidden: true,
    giverNpcId: "ai-hollow",
    title: "The Last One Standing",
    description: "Yuuki survived a full party wipe on launch day and has refused to party with anyone since.",
    objectives: [
      { id: "find-locket", text: "Find out what the cracked locket near the field wipe site means." },
      { id: "confront-hollow", text: "Decide whether to push Yuuki about it." },
    ],
    rewardSummary: "Can recruit Yuuki into your party if handled carefully.",
  },
  {
    id: "ai-q-side-supply-run",
    worldId: "aincrad",
    type: "side",
    giverNpcId: "ai-dask",
    title: "Supply Run",
    description: "Agil needs iron ore from the field brought back before the market corners itself.",
    objectives: [{ id: "collect-ore", text: "Collect 5 Iron Ore from field enemies." }, { id: "deliver", text: "Deliver it to Agil." }],
    rewardSummary: "Col and a discount at the Stonebreakers' shop.",
  },
  {
    id: "ai-q-side-lost-scout",
    worldId: "aincrad",
    type: "rescue",
    title: "The Lost Scout",
    description: "A player went missing scouting the dungeon entrance. Their guild is offering a reward for information.",
    objectives: [{ id: "find-scout", text: "Find the missing scout." }, { id: "decide-fate", text: "Decide how to help." }],
    rewardSummary: "A guaranteed rare drop and goodwill from whichever guild you inform.",
  },
  {
    id: "ai-q-side-mei-commission",
    worldId: "aincrad",
    type: "collection",
    giverNpcId: "ai-mei",
    title: "Rare Materials Commission",
    description: "Lisbeth wants Beast Hide from field wolves to prototype a new armor design.",
    objectives: [{ id: "collect-hide", text: "Collect 3 Beast Hide." }, { id: "deliver-hide", text: "Deliver it to Lisbeth." }],
    rewardSummary: "A discounted custom-crafted piece of armor.",
  },
  {
    id: "ai-q-hidden-floor1-shrine",
    worldId: "aincrad",
    type: "hidden",
    hidden: true,
    title: "The Forgotten Shrine",
    description: "A hidden clearing deep in the Floor 1 field holds something that isn't on any map.",
    objectives: [{ id: "find-shrine", text: "Find the hidden shrine." }],
    rewardSummary: "A codex secret and a rare accessory.",
  },
  {
    id: "ai-q-hidden-floor2-cache",
    worldId: "aincrad",
    type: "hidden",
    hidden: true,
    title: "The Frozen Cache",
    description: "Rumors describe a supply cache frozen into Mistfallen Reach's cliffs since the game's first week.",
    objectives: [{ id: "find-cache", text: "Find the frozen cache." }],
    rewardSummary: "A rare crafting material stash.",
  },
  {
    id: "ai-q-hidden-floor3-vigil",
    worldId: "aincrad",
    type: "hidden",
    hidden: true,
    title: "The Vigil",
    description: "Someone has been leaving lit candles at the edge of Ashen Hollow's dungeon every day since launch.",
    objectives: [{ id: "find-vigil-keeper", text: "Find out who's keeping the vigil, and why." }],
    rewardSummary: "A quiet, optional piece of Aincrad's larger story.",
  },
  {
    id: "ai-q-guild-recruit",
    worldId: "aincrad",
    type: "guild",
    title: "Choosing a Banner",
    description: "Three guilds on Floor 1 would take you, each for different reasons.",
    objectives: [{ id: "meet-leaders", text: "Meet the three guild leaders." }, { id: "choose-guild", text: "Choose a guild, or stay solo." }],
    rewardSummary: "Shapes your party options and reputation for the rest of the game.",
  },
  {
    id: "ai-q-choirkeeper-past",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-choirkeeper",
    title: "Why the Choirkeeper Stayed",
    description: "One of the first players to reach Floor 7 never continued climbing. Nobody knows why — except, maybe, them.",
    objectives: [{ id: "earn-trust", text: "Earn enough trust for the Choirkeeper to speak above a whisper." }, { id: "learn-why", text: "Learn why they chose to stay." }],
    hidden: true,
    rewardSummary: "A quiet, optional piece of Aincrad's larger story.",
  },
  {
    id: "ai-q-ilyana-guilt",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-ilyana",
    title: "The First Attempt",
    description: "Ilyana pulled out of the first attempt on the Tenth Gate at the last minute. The rest of that party never came back.",
    objectives: [{ id: "learn-history", text: "Learn what happened to the first attempt." }, { id: "decide-role", text: "Decide what role she plays in yours." }],
    rewardSummary: "Affects whether Ilyana joins the final boss raid.",
  },
  {
    id: "ai-q-corvin-ledger",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-corvin",
    title: "The Second Ledger",
    description: "Corvin keeps an unofficial ledger of names the system itself deleted after certain floor incidents — proof something was scrubbed from the record.",
    objectives: [{ id: "learn-ledger", text: "Learn what the second ledger actually records." }, { id: "decide-role", text: "Decide whether Corvin marches with you." }],
    rewardSummary: "Affects whether Corvin joins the Floor 15 boss raid.",
  },
  {
    id: "ai-q-renn-pride",
    worldId: "aincrad",
    type: "character",
    giverNpcId: "ai-renn",
    title: "Two Failed Attempts",
    description: "Renn has attempted the Twentieth Spire's boss alone, twice, and lost both times. She doesn't want anyone to know how close it came to being three.",
    objectives: [{ id: "learn-attempts", text: "Learn about her two failed attempts." }, { id: "decide-role", text: "Decide whether she attempts the Spire with you instead." }],
    rewardSummary: "Affects whether Renn joins the Floor 20 boss raid.",
  },
];
