import type { SceneInput } from "@/types";

const W = "aincrad" as const;
const C = "ai-ch1" as const;

export const aincradScenes: SceneInput[] = [
  /* ------------------------------- Opening ------------------------------- */
  {
    id: "ai-scene-login",
    worldId: W,
    chapterId: C,
    title: "Full Dive",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "\"Link Start.\" The world resolves around you — stone plazas, a sky with too many floating panels, a castle that goes up farther than your eyes want to follow.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ai-codex-aincrad" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Every player in the plaza is dragged into the same forced menu at once. A hooded figure appears above the crowd, and the menu resolves into a single word: LOGOUT — grayed out. Disabled.",
        next: "n3",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        speakerId: undefined,
        speakerName: "Game Master",
        expression: "neutral",
        text: "\"There is no logout button in this world. If your HP reaches zero, the NerveGear will destroy your brain. There is only one way to leave Aincrad: clear all one hundred floors.\"",
        next: "n4",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-no-logout-revealed" }, { type: "unlockCodex", entryId: "ai-codex-nerve-gear" }, { type: "unlockAchievement", achievementId: "ach-locked-in" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        expression: "shocked",
        isInnerMonologue: true,
        text: "The plaza is screaming, crying, going quiet in waves. Somewhere out there, everyone you know just watched your body go still in a hospital bed or bedroom, waiting.",
        isInterruption: false,
        effects: [{ type: "startQuest", questId: "ai-q-main-locked-sky" }, { type: "changeLocation", mapId: "ai-map-town1", spawnId: "default" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- NPC introductions ---------------------------- */
  {
    id: "ai-scene-kirei-intro",
    worldId: W,
    chapterId: C,
    title: "Kirei Sanjo",
    startNode: "n1",
    altEntryNodes: ["n1", "revisit"],
    nodes: [
      {
        id: "n1",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "smirk",
        text: "You're not panicking. Good. Half this plaza is still on the floor. I'm Kirei — I ran the closed beta for this floor, so I actually know what's coming.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-kirei" }, { type: "unlockCodex", entryId: "ai-codex-kirei" }],
        choices: [],
        conditions: [{ type: "missingFlag", flag: "ai-flag-met-kirei" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"Teach me what you know. I'll owe you.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: 8 }, { type: "modifyRelationship", npcId: "ai-kirei", axis: "respect", delta: 4 }],
          },
          {
            id: "c2",
            text: "\"Why help a stranger instead of just surviving alone?\"",
            requirementLabel: "Requires Perception 5",
            conditions: [{ type: "minStat", stat: "perception", value: 5 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-kirei", axis: "respect", delta: 5 }],
            goTo: "n3",
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "worried",
        text: "...Because being alone with what I know sounds worse than sharing it. Don't make it weird.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "revisit",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "neutral",
        text: "Field's northeast, dungeon's past that. Don't die doing something stupid, it reflects badly on my teaching.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [{ type: "flag", flag: "ai-flag-met-kirei" }],
      },
    ],
  },
  {
    id: "ai-scene-kirei-secret",
    worldId: W,
    chapterId: C,
    title: "What Happened in the Beta",
    startNode: "n1",
    altEntryNodes: ["n1", "afterward", "not-yet"],
    nodes: [
      {
        id: "n1",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "worried",
        text: "...Can I tell you something? During the beta's tutorial boss, I froze. Completely. Someone covered for me and the fight killed his stamina bar down to nothing — in beta that just meant a respawn timer. Here it wouldn't.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-kirei-secret-told" }, { type: "startQuest", questId: "ai-q-kirei-freeze" }],
        choices: [],
        conditions: [{ type: "flag", flag: "ai-flag-met-kirei" }, { type: "relationship", npcId: "ai-kirei", axis: "trust", min: 15 }, { type: "missingFlag", flag: "ai-flag-kirei-secret-told" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"That won't happen again. I'll be there.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-kirei-supported" },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: 15 },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "affection", delta: 10 },
              { type: "completeQuest", questId: "ai-q-kirei-freeze", outcome: "supported" },
            ],
            goTo: "good",
          },
          {
            id: "c2",
            text: "\"Then maybe you shouldn't be on the front line for the boss raid.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-kirei-benched" },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: -10 },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "respect", delta: -5 },
              { type: "completeQuest", questId: "ai-q-kirei-freeze", outcome: "benched" },
            ],
            goTo: "hard",
          },
        ],
      },
      { id: "good", speakerId: "ai-kirei", speakerName: "Kirei", expression: "smile", text: "...Okay. Okay. Thank you. I mean that.", isInterruption: false, effects: [], choices: [], conditions: [] },
      { id: "hard", speakerId: "ai-kirei", speakerName: "Kirei", expression: "shocked", text: "...Wow. Okay. Noted. I'll just — go figure that out myself, then.", isInterruption: false, effects: [], choices: [], conditions: [] },
      { id: "afterward", speakerId: "ai-kirei", speakerName: "Kirei", expression: "neutral", text: "Ready when you are.", isInterruption: false, effects: [], choices: [], conditions: [{ type: "flag", flag: "ai-flag-kirei-secret-told" }] },
      { id: "not-yet", speakerId: "ai-kirei", speakerName: "Kirei", expression: "neutral", text: "You need something? Kind of in the middle of pretending I'm fine here.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-toran-intro",
    worldId: W,
    chapterId: C,
    title: "Toran Voss",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-toran",
        speakerName: "Toran",
        expression: "smile",
        text: "You've got the look of someone doing math on how many floors this'll take. Toran. I'm older than most of the launch cohort — figured I'd hold the line up here while I still can.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-toran" }, { type: "unlockCodex", entryId: "ai-codex-toran" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "Something about \"while I still can\" sits strangely.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ai-scene-mei-forge",
    worldId: W,
    chapterId: C,
    title: "Mei's Forge",
    startNode: "n1",
    altEntryNodes: ["n1", "shop"],
    nodes: [
      {
        id: "n1",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "smile",
        text: "New face! Come in, come in — I don't fight, so this forge is the one thing in Aincrad I still have full control over. What do you need?",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-mei" }, { type: "unlockCodex", entryId: "ai-codex-mei" }],
        conditions: [{ type: "missingFlag", flag: "ai-flag-met-mei" }],
        choices: [
          {
            id: "c1",
            text: "\"Why don't you fight?\"",
            requirementLabel: "Requires Empathy 5",
            conditions: [{ type: "minStat", stat: "empathy", value: 5 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-mei", axis: "trust", delta: 6 }],
            goTo: "why",
          },
          { id: "c2", text: "Browse her wares.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [], goTo: "shop" },
        ],
      },
      { id: "why", speakerId: "ai-mei", speakerName: "Mei", expression: "worried", text: "...Long story. Short version: I'm not supposed to be the one who logged in. Let's leave it there for now.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-mei-hint" }], choices: [], conditions: [], next: "shop" },
      {
        id: "shop",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "smile",
        text: "Here's what I've got in stock today.",
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "buy-blade", text: "Buy Iron Blade — 300 col", requirementLabel: "Requires 300 Col", conditions: [{ type: "minStat", stat: "col", value: 300 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -300 }, { type: "addItem", itemId: "ai-item-iron-blade", quantity: 1 }], goTo: "shop" },
          { id: "buy-vest", text: "Buy Reinforced Coat — 350 col", requirementLabel: "Requires 350 Col", conditions: [{ type: "minStat", stat: "col", value: 350 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -350 }, { type: "addItem", itemId: "ai-item-reinforced-coat", quantity: 1 }], goTo: "shop" },
          { id: "leave", text: "Leave", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-mei-brother",
    worldId: W,
    chapterId: C,
    title: "The Slot That Wasn't Hers",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "sad",
        text: "You asked before why I don't fight. Truth is — this NerveGear slot belonged to my brother. He preordered it for launch day. I used it instead, because I wanted to see the game he wouldn't shut up about.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-mei-secret-told" }, { type: "startQuest", questId: "ai-q-mei-brother" }],
        choices: [],
        conditions: [{ type: "flag", flag: "ai-flag-mei-hint" }, { type: "relationship", npcId: "ai-mei", axis: "trust", min: 20 }, { type: "missingFlag", flag: "ai-flag-mei-secret-told" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "\"That's not your fault. He's safe out there — you're the one who's stuck.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-mei", axis: "affection", delta: 10 }, { type: "modifyRelationship", npcId: "ai-mei", axis: "trust", delta: 10 }, { type: "completeQuest", questId: "ai-q-mei-brother", outcome: "comforted" }, { type: "unlockCodex", entryId: "ai-codex-mei-secret" }, { type: "sendMessage", npcId: "ai-mei", messageId: "ai-msg-mei-thanks" }] },
          { id: "c2", text: "Say nothing. Let her sit with it.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: true, effects: [{ type: "modifyRelationship", npcId: "ai-mei", axis: "trust", delta: 5 }, { type: "completeQuest", questId: "ai-q-mei-brother", outcome: "witnessed" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-ryo-intro",
    worldId: W,
    chapterId: C,
    title: "Ryo Katsuragi",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-ryo",
        speakerName: "Ryo",
        expression: "smile",
        text: "New blood! I'm Ryo — Iron Vanguard. We're the guild that's actually going to clear this game, not just survive it. You look like you can hold a sword. Interested?",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-ryo" }, { type: "unlockCodex", entryId: "ai-codex-ryo" }],
        conditions: [],
        choices: [],
      },
    ],
  },
  {
    id: "ai-scene-nell-intro",
    worldId: W,
    chapterId: C,
    title: "Nell Farrow",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-nell",
        speakerName: "Nell",
        expression: "smile",
        text: "Hi — sorry, I know everyone's recruiting you today. I run Hearthlight. We're small. We just... try not to lose anyone. That's really the whole pitch.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-nell" }, { type: "unlockCodex", entryId: "ai-codex-nell" }],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"That's a good pitch, actually.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-nell", axis: "affection", delta: 6 }, { type: "modifyRelationship", npcId: "ai-nell", axis: "trust", delta: 5 }],
          },
          { id: "c2", text: "\"Small guilds fold first when things get bad.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-nell", axis: "respect", delta: -3 }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-dask-intro",
    worldId: W,
    chapterId: C,
    title: "Dask Orrin",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-dask",
        speakerName: "Dask",
        expression: "neutral",
        text: "Stonebreakers. We don't fight if we can help it. Somebody has to keep col moving and gear in stock, or this whole floor starves before floor two opens. You want in, you're useful even without a sword.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-dask" }, { type: "unlockCodex", entryId: "ai-codex-dask" }],
        conditions: [],
        choices: [],
      },
    ],
  },
  {
    id: "ai-scene-hollow-intro",
    worldId: W,
    chapterId: C,
    title: "\"Hollow\"",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-hollow",
        speakerName: "Hollow",
        expression: "cold",
        text: "Don't. I'm not recruiting and I'm not joining anything. Just move along.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-hollow" }, { type: "unlockCodex", entryId: "ai-codex-hollow" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Leave without pushing.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: true,
            effects: [{ type: "modifyRelationship", npcId: "ai-hollow", axis: "respect", delta: 5 }],
          },
          {
            id: "c2",
            text: "\"Something happened to you out there.\"",
            requirementLabel: "Requires Perception 6",
            conditions: [{ type: "minStat", stat: "perception", value: 6 }],
            hiddenIfUnmet: true,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-hollow", axis: "suspicion", delta: 10 }, { type: "modifyRelationship", npcId: "ai-hollow", axis: "respect", delta: 3 }, { type: "setFlag", flag: "ai-flag-hollow-noticed" }],
            goTo: "n3",
          },
        ],
      },
      { id: "n3", speakerId: "ai-hollow", speakerName: "Hollow", expression: "worried", text: "...Careful. Keep guessing like that and I'll start guessing back.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-hollow-field",
    worldId: W,
    chapterId: C,
    title: "Hollow, Alone in the Field",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-hollow",
        speakerName: "Hollow",
        expression: "cold",
        text: "This isn't a good spot to linger. A party wiped here on launch day. I know because I was the only one who walked out.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-hollow-wipe-mentioned" }, { type: "startQuest", questId: "ai-q-hollow-past" }],
        choices: [],
        conditions: [{ type: "missingFlag", flag: "ai-flag-hollow-wipe-mentioned" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "There's a locket half-buried nearby, if you look closely.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ai-scene-hollow-recruit",
    worldId: W,
    chapterId: C,
    title: "Asking Hollow to Party Up",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        text: "You could try asking Hollow to join you for the boss raid, now that they know you found the locket.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [{ type: "hasItem", itemId: "ai-item-hollow-locket", quantity: 1 }, { type: "missingFlag", flag: "ai-flag-hollow-recruited" }],
        choices: [
          {
            id: "c1",
            text: "\"You don't have to be alone for this one.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-hollow-recruited" },
              { type: "modifyRelationship", npcId: "ai-hollow", axis: "trust", delta: 20 },
              { type: "modifyRelationship", npcId: "ai-hollow", axis: "affection", delta: 8 },
              { type: "completeQuest", questId: "ai-q-hollow-past", outcome: "recruited" },
              { type: "unlockAchievement", achievementId: "ach-unlikely-ally" },
            ],
            goTo: "good",
          },
          {
            id: "c2",
            text: "Return the locket and leave it at that.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-hollow", axis: "trust", delta: 8 }, { type: "completeQuest", questId: "ai-q-hollow-past", outcome: "respected-distance" }],
          },
        ],
      },
      { id: "good", speakerId: "ai-hollow", speakerName: "Hollow", expression: "worried", text: "...Fine. Once. Don't make me regret it.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-archivist-intro",
    worldId: W,
    chapterId: C,
    title: "The Archivist",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-arch",
        speakerName: "Archivist",
        expression: "neutral",
        text: "Welcome, player. I sell information the system doesn't strictly want you to have. Fair prices. Perfect accuracy. No further questions answered about what I am.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-archivist" }, { type: "unlockCodex", entryId: "ai-codex-archivist" }],
        conditions: [],
        choices: [
          { id: "c1", text: "\"Are you a player?\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [], goTo: "dodge" },
          { id: "c2", text: "Leave it alone.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: true, effects: [] },
        ],
      },
      { id: "dodge", speakerId: "ai-arch", speakerName: "Archivist", expression: "smile", text: "That question is outside what I'm permitted to sell an answer to. Ask me about the boss instead.", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-archivist-mystery" }], choices: [], conditions: [] },
    ],
  },

  /* ---------------------------- Utility / town scenes ---------------------------- */
  {
    id: "ai-scene-inn",
    worldId: W,
    chapterId: C,
    title: "Rest",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "You pay a few col for a real bed instead of the ground. It's a small mercy, but you take it.", isInterruption: false, effects: [{ type: "modifyStat", stat: "health", delta: 999 }, { type: "modifyStat", stat: "stamina", delta: 999 }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-item-shop",
    worldId: W,
    chapterId: C,
    title: "Item Shop",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: false,
        text: "The shop's wares, laid out on a cloth counter.",
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "buy-heal", text: "Buy Healing Crystal — 30 col", requirementLabel: "Requires 30 Col", conditions: [{ type: "minStat", stat: "col", value: 30 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -30 }, { type: "addItem", itemId: "ai-item-healing-crystal", quantity: 1 }], goTo: "n1" },
          { id: "buy-stamina", text: "Buy Stamina Draught — 25 col", requirementLabel: "Requires 25 Col", conditions: [{ type: "minStat", stat: "col", value: 25 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -25 }, { type: "addItem", itemId: "ai-item-stamina-draught", quantity: 1 }], goTo: "n1" },
          { id: "buy-teleport", text: "Buy Teleport Crystal — 200 col", requirementLabel: "Requires 200 Col", conditions: [{ type: "minStat", stat: "col", value: 200 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -200 }, { type: "addItem", itemId: "ai-item-teleport-crystal", quantity: 1 }], goTo: "n1" },
          { id: "leave", text: "Leave", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-tavern",
    worldId: W,
    chapterId: C,
    title: "The Cracked Bell Tavern",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Half the tavern is trading rumors about the field boss. The other half is pretending not to listen for their own name on the day's casualty list.", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-town-of-beginnings" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-guild-board",
    worldId: W,
    chapterId: C,
    title: "Guild Recruitment Board",
    startNode: "n1",
    altEntryNodes: ["n1", "chosen"],
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: false,
        text: "Three banners are pinned to the board: Iron Vanguard, Hearthlight, Stonebreakers. Or you could tear none of them down and stay solo.",
        isInterruption: false,
        effects: [{ type: "startQuest", questId: "ai-q-guild-recruit" }],
        conditions: [{ type: "missingFlag", flag: "ai-flag-guild-chosen" }],
        choices: [
          {
            id: "c1",
            text: "Join the Iron Vanguard.",
            requirementLabel: "Requires having met Ryo",
            conditions: [{ type: "flag", flag: "ai-flag-met-ryo" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-vanguard" },
              { type: "modifyStat", stat: "combat", delta: 1 },
              { type: "modifyRelationship", npcId: "ai-ryo", axis: "loyalty", delta: 15 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "vanguard" },
            ],
            goTo: "chosen",
          },
          {
            id: "c2",
            text: "Join Hearthlight.",
            requirementLabel: "Requires having met Nell",
            conditions: [{ type: "flag", flag: "ai-flag-met-nell" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-hearthlight" },
              { type: "modifyStat", stat: "empathy", delta: 1 },
              { type: "modifyRelationship", npcId: "ai-nell", axis: "loyalty", delta: 15 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "hearthlight" },
            ],
            goTo: "chosen",
          },
          {
            id: "c3",
            text: "Join the Stonebreakers.",
            requirementLabel: "Requires having met Dask",
            conditions: [{ type: "flag", flag: "ai-flag-met-dask" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-stonebreakers" },
              { type: "modifyStat", stat: "col", delta: 500 },
              { type: "modifyRelationship", npcId: "ai-dask", axis: "loyalty", delta: 15 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "stonebreakers" },
            ],
            goTo: "chosen",
          },
          {
            id: "c4",
            text: "Stay solo. You trust your own blade more than a banner.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-solo" },
              { type: "modifyStat", stat: "discipline", delta: 1 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "solo" },
              { type: "unlockAchievement", achievementId: "ach-lone-swordsman" },
            ],
            goTo: "chosen",
          },
        ],
      },
      { id: "chosen", expression: "neutral", isInnerMonologue: true, text: "Your choice is posted. Whatever comes next on this floor, you won't be facing it as a total unknown anymore.", isInterruption: false, effects: [], choices: [], conditions: [{ type: "flag", flag: "ai-flag-guild-chosen" }] },
    ],
  },
  {
    id: "ai-scene-tutorial-quest",
    worldId: W,
    chapterId: C,
    title: "Training Quest",
    startNode: "n1",
    altEntryNodes: ["n1", "done"],
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "A system NPC runs you through the basics: sword skills draw from a stamina pool, timing your input during the skill's motion adds bonus damage. You drill it against a dummy until it's muscle memory.",
        isInterruption: false,
        effects: [
          { type: "setFlag", flag: "ai-flag-tutorial-complete" },
          { type: "modifyStat", stat: "swordSkill", delta: 2 },
          { type: "unlockCodex", entryId: "ai-codex-sword-skills" },
          { type: "sendMessage", npcId: "ai-kirei", messageId: "ai-msg-kirei-checklist" },
        ],
        conditions: [{ type: "missingFlag", flag: "ai-flag-tutorial-complete" }],
        choices: [],
      },
      { id: "done", expression: "neutral", isInnerMonologue: true, text: "You've already drilled this. The dummy has seen better days.", isInterruption: false, effects: [], choices: [], conditions: [{ type: "flag", flag: "ai-flag-tutorial-complete" }] },
    ],
  },
  {
    id: "ai-scene-hidden-shrine",
    worldId: W,
    chapterId: C,
    title: "The Forgotten Shrine",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "A perfectly circular clearing, moss-covered stones arranged in a ring that has nothing to do with any quest marker. It feels deliberate — like part of Aincrad the developers never meant players to find this early.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-found-shrine" }, { type: "completeQuest", questId: "ai-q-hidden-floor1-shrine" }, { type: "unlockCodex", entryId: "ai-codex-shrine-secret" }, { type: "addItem", itemId: "ai-item-beginner-ring", quantity: 1 }, { type: "unlockAchievement", achievementId: "ach-off-the-map" }],
        conditions: [],
        choices: [],
      },
    ],
  },
  {
    id: "ai-scene-vigil",
    worldId: W,
    chapterId: C,
    title: "The Vigil",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Candles, relit every day by hands nobody's ever caught in the act. Names are scratched into the stone beneath them — none you recognize, all clearly real people.", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-vigil" }], choices: [], conditions: [] },
    ],
  },

  /* ---------------------------- Boss Raid: Floor 1 ---------------------------- */
  {
    id: "ai-scene-boss1-prep",
    worldId: W,
    chapterId: C,
    title: "Raid Preparation — Sylvan Guardian",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "This is it. Whatever's waiting past this chamber decides whether Floor 1 opens up or closes on someone's name.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ai-codex-sylvan-guardian" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Focus fire the core once its bark plating breaks — high risk, fast kill.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-aggressive" }],
          },
          {
            id: "c2",
            text: "Rotate guard duty so no one takes consecutive hits — slower, safer.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-cautious" }],
          },
          {
            id: "c3",
            text: "Use analyze skills first to map its full attack pattern before committing.",
            requirementLabel: "Requires Intelligence 6",
            conditions: [{ type: "minStat", stat: "intelligence", value: 6 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-analyzed" }, { type: "modifyStat", stat: "threatLevel", delta: -5 }],
          },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss1-aftermath",
    worldId: W,
    chapterId: C,
    title: "After the Guardian",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The Guardian's core dims and the chamber's roots retract into the walls. Floor 1's boss is down. Somewhere below, the announcement rings out across every player's HUD at once.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "addItem", itemId: "ai-item-floor1-unique", quantity: 1 }, { type: "unlockAchievement", achievementId: "ach-floor-pioneer" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "In the middle of the celebration, you notice someone's stamina bar in the corner of the party display flickering red. A decision has to be made in the next few seconds.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Break formation to cover them yourself.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            timerSeconds: 8,
            effects: [
              { type: "setFlag", flag: "ai-flag-zero-casualties" },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: 10 },
              { type: "modifyRelationship", npcId: "ai-toran", axis: "respect", delta: 10 },
              { type: "unlockAchievement", achievementId: "ach-zero-casualties" },
            ],
            goTo: "safe",
          },
          {
            id: "c2",
            text: "Trust the formation to hold and stay on the boss's attack pattern.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            timerSeconds: 8,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-casualty" }, { type: "modifyRelationship", npcId: "ai-toran", axis: "respect", delta: -8 }],
            goTo: "cost",
          },
        ],
      },
      { id: "safe", expression: "neutral", isInnerMonologue: true, text: "It's close, but everyone's still standing when the boss's health hits zero. Floor 1, cleared. Nobody's name gets added to a list today.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch1-complete" }, { type: "goToScene", sceneId: "ai-scene-chapter-recap-trigger" }], choices: [], conditions: [] },
      { id: "cost", expression: "sad", isInnerMonologue: true, text: "The boss falls. So does someone else, a second too late for anyone to reach. Floor 1 is cleared. It doesn't feel like a victory in the way you expected.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch1-complete" }, { type: "goToScene", sceneId: "ai-scene-chapter-recap-trigger" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-chapter-recap-trigger",
    worldId: W,
    chapterId: C,
    title: "One Floor Down",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Ninety-nine floors left. The Town of Beginnings looks different now — less like a waypoint, more like the first room of somewhere you actually live.",
        isInterruption: false,
        effects: [{ type: "unlockAchievement", achievementId: "ach-one-floor-down" }],
        choices: [],
        conditions: [],
      },
    ],
  },
];
