import type { SceneInput } from "@/types";

const W = "aincrad" as const;
const C = "ai-ch1" as const;

export const aincradScenes: SceneInput[] = [
  /* ------------------------------- Opening ------------------------------- */
  {
    id: "ai-scene-login",
    worldId: W,
    chapterId: C,
    title: "Full Dive",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "\"Link Start.\" The world resolves around you — stone plazas, a sky with too many floating panels, a castle that goes up farther than your eyes want to follow.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ai-codex-aincrad" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Every player in the plaza is dragged into the same forced menu at once. A hooded figure appears above the crowd, and the menu resolves into a single word: LOGOUT — grayed out. Disabled.",
        next: "n3",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        speakerId: undefined,
        speakerName: "Game Master",
        expression: "neutral",
        text: "\"There is no logout button in this world. If your HP reaches zero, the NerveGear will destroy your brain. There is only one way to leave Aincrad: clear all one hundred floors.\"",
        next: "n4",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-no-logout-revealed" }, { type: "unlockCodex", entryId: "ai-codex-nerve-gear" }, { type: "unlockAchievement", achievementId: "ach-locked-in" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n4",
        expression: "shocked",
        isInnerMonologue: true,
        text: "The plaza is screaming, crying, going quiet in waves. Somewhere out there, everyone you know just watched your body go still in a hospital bed or bedroom, waiting.",
        isInterruption: false,
        effects: [{ type: "startQuest", questId: "ai-q-main-locked-sky" }, { type: "changeLocation", mapId: "ai-map-town1", spawnId: "default" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ---------------------------- NPC introductions ---------------------------- */
  {
    id: "ai-scene-kirei-intro",
    worldId: W,
    chapterId: C,
    title: "Kirei Sanjo",
    startNode: "n1",
    altEntryNodes: ["n1", "revisit"],
    nodes: [
      {
        id: "n1",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "smirk",
        text: "You're not panicking. Good. Half this plaza is still on the floor. I'm Kirei — I ran the closed beta for this floor, so I actually know what's coming.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-kirei" }, { type: "unlockCodex", entryId: "ai-codex-kirei" }],
        choices: [],
        conditions: [{ type: "missingFlag", flag: "ai-flag-met-kirei" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"Teach me what you know. I'll owe you.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: 8 }, { type: "modifyRelationship", npcId: "ai-kirei", axis: "respect", delta: 4 }],
          },
          {
            id: "c2",
            text: "\"Why help a stranger instead of just surviving alone?\"",
            requirementLabel: "Requires Perception 5",
            conditions: [{ type: "minStat", stat: "perception", value: 5 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-kirei", axis: "respect", delta: 5 }],
            goTo: "n3",
          },
        ],
      },
      {
        id: "n3",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "worried",
        text: "...Because being alone with what I know sounds worse than sharing it. Don't make it weird.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "revisit",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "neutral",
        text: "Field's northeast, dungeon's past that. Don't die doing something stupid, it reflects badly on my teaching.",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [{ type: "flag", flag: "ai-flag-met-kirei" }],
      },
    ],
  },
  {
    id: "ai-scene-kirei-secret",
    worldId: W,
    chapterId: C,
    title: "What Happened in the Beta",
    startNode: "n1",
    altEntryNodes: ["n1", "afterward", "not-yet"],
    nodes: [
      {
        id: "n1",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "worried",
        text: "...Can I tell you something? During the beta's tutorial boss, I froze. Completely. Someone covered for me and the fight killed his stamina bar down to nothing — in beta that just meant a respawn timer. Here it wouldn't.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-kirei-secret-told" }, { type: "startQuest", questId: "ai-q-kirei-freeze" }],
        choices: [],
        conditions: [{ type: "flag", flag: "ai-flag-met-kirei" }, { type: "relationship", npcId: "ai-kirei", axis: "trust", min: 15 }, { type: "missingFlag", flag: "ai-flag-kirei-secret-told" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"That won't happen again. I'll be there.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-kirei-supported" },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: 15 },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "affection", delta: 10 },
              { type: "completeQuest", questId: "ai-q-kirei-freeze", outcome: "supported" },
            ],
            goTo: "good",
          },
          {
            id: "c2",
            text: "\"Then maybe you shouldn't be on the front line for the boss raid.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-kirei-benched" },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: -10 },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "respect", delta: -5 },
              { type: "completeQuest", questId: "ai-q-kirei-freeze", outcome: "benched" },
            ],
            goTo: "hard",
          },
        ],
      },
      { id: "good", speakerId: "ai-kirei", speakerName: "Kirei", expression: "smile", text: "...Okay. Okay. Thank you. I mean that.", isInterruption: false, effects: [], choices: [], conditions: [] },
      { id: "hard", speakerId: "ai-kirei", speakerName: "Kirei", expression: "shocked", text: "...Wow. Okay. Noted. I'll just — go figure that out myself, then.", isInterruption: false, effects: [], choices: [], conditions: [] },
      { id: "afterward", speakerId: "ai-kirei", speakerName: "Kirei", expression: "neutral", text: "Ready when you are.", isInterruption: false, effects: [], choices: [], conditions: [{ type: "flag", flag: "ai-flag-kirei-secret-told" }] },
      { id: "not-yet", speakerId: "ai-kirei", speakerName: "Kirei", expression: "neutral", text: "You need something? Kind of in the middle of pretending I'm fine here.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-toran-intro",
    worldId: W,
    chapterId: C,
    title: "Toran Voss",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-toran",
        speakerName: "Toran",
        expression: "smile",
        text: "You've got the look of someone doing math on how many floors this'll take. Toran. I'm older than most of the launch cohort — figured I'd hold the line up here while I still can.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-toran" }, { type: "unlockCodex", entryId: "ai-codex-toran" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "Something about \"while I still can\" sits strangely.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ai-scene-mei-forge",
    worldId: W,
    chapterId: C,
    title: "Mei's Forge",
    startNode: "n1",
    altEntryNodes: ["n1", "shop"],
    nodes: [
      {
        id: "n1",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "smile",
        text: "New face! Come in, come in — I don't fight, so this forge is the one thing in Aincrad I still have full control over. What do you need?",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-mei" }, { type: "unlockCodex", entryId: "ai-codex-mei" }],
        conditions: [{ type: "missingFlag", flag: "ai-flag-met-mei" }],
        choices: [
          {
            id: "c1",
            text: "\"Why don't you fight?\"",
            requirementLabel: "Requires Empathy 5",
            conditions: [{ type: "minStat", stat: "empathy", value: 5 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-mei", axis: "trust", delta: 6 }],
            goTo: "why",
          },
          { id: "c2", text: "Browse her wares.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [], goTo: "shop" },
        ],
      },
      { id: "why", speakerId: "ai-mei", speakerName: "Mei", expression: "worried", text: "...Long story. Short version: I'm not supposed to be the one who logged in. Let's leave it there for now.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-mei-hint" }], choices: [], conditions: [], next: "shop" },
      {
        id: "shop",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "smile",
        text: "Here's what I've got in stock today.",
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "buy-blade", text: "Buy Iron Blade — 300 col", requirementLabel: "Requires 300 Col", conditions: [{ type: "minStat", stat: "col", value: 300 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -300 }, { type: "addItem", itemId: "ai-item-iron-blade", quantity: 1 }], goTo: "shop" },
          { id: "buy-vest", text: "Buy Reinforced Coat — 350 col", requirementLabel: "Requires 350 Col", conditions: [{ type: "minStat", stat: "col", value: 350 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -350 }, { type: "addItem", itemId: "ai-item-reinforced-coat", quantity: 1 }], goTo: "shop" },
          { id: "leave", text: "Leave", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-mei-brother",
    worldId: W,
    chapterId: C,
    title: "The Slot That Wasn't Hers",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "sad",
        text: "You asked before why I don't fight. Truth is — this NerveGear slot belonged to my brother. He preordered it for launch day. I used it instead, because I wanted to see the game he wouldn't shut up about.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-mei-secret-told" }, { type: "startQuest", questId: "ai-q-mei-brother" }],
        choices: [],
        conditions: [{ type: "flag", flag: "ai-flag-mei-hint" }, { type: "relationship", npcId: "ai-mei", axis: "trust", min: 20 }, { type: "missingFlag", flag: "ai-flag-mei-secret-told" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "\"That's not your fault. He's safe out there — you're the one who's stuck.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-mei", axis: "affection", delta: 10 }, { type: "modifyRelationship", npcId: "ai-mei", axis: "trust", delta: 10 }, { type: "completeQuest", questId: "ai-q-mei-brother", outcome: "comforted" }, { type: "unlockCodex", entryId: "ai-codex-mei-secret" }, { type: "sendMessage", npcId: "ai-mei", messageId: "ai-msg-mei-thanks" }] },
          { id: "c2", text: "Say nothing. Let her sit with it.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: true, effects: [{ type: "modifyRelationship", npcId: "ai-mei", axis: "trust", delta: 5 }, { type: "completeQuest", questId: "ai-q-mei-brother", outcome: "witnessed" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-ryo-intro",
    worldId: W,
    chapterId: C,
    title: "Ryo Katsuragi",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-ryo",
        speakerName: "Ryo",
        expression: "smile",
        text: "New blood! I'm Ryo — Iron Vanguard. We're the guild that's actually going to clear this game, not just survive it. You look like you can hold a sword. Interested?",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-ryo" }, { type: "unlockCodex", entryId: "ai-codex-ryo" }],
        conditions: [],
        choices: [],
      },
    ],
  },
  {
    id: "ai-scene-nell-intro",
    worldId: W,
    chapterId: C,
    title: "Nell Farrow",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-nell",
        speakerName: "Nell",
        expression: "smile",
        text: "Hi — sorry, I know everyone's recruiting you today. I run Hearthlight. We're small. We just... try not to lose anyone. That's really the whole pitch.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-nell" }, { type: "unlockCodex", entryId: "ai-codex-nell" }],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "\"That's a good pitch, actually.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-nell", axis: "affection", delta: 6 }, { type: "modifyRelationship", npcId: "ai-nell", axis: "trust", delta: 5 }],
          },
          { id: "c2", text: "\"Small guilds fold first when things get bad.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-nell", axis: "respect", delta: -3 }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-dask-intro",
    worldId: W,
    chapterId: C,
    title: "Dask Orrin",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-dask",
        speakerName: "Dask",
        expression: "neutral",
        text: "Stonebreakers. We don't fight if we can help it. Somebody has to keep col moving and gear in stock, or this whole floor starves before floor two opens. You want in, you're useful even without a sword.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-dask" }, { type: "unlockCodex", entryId: "ai-codex-dask" }],
        conditions: [],
        choices: [],
      },
    ],
  },
  {
    id: "ai-scene-hollow-intro",
    worldId: W,
    chapterId: C,
    title: "\"Hollow\"",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-hollow",
        speakerName: "Hollow",
        expression: "cold",
        text: "Don't. I'm not recruiting and I'm not joining anything. Just move along.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-hollow" }, { type: "unlockCodex", entryId: "ai-codex-hollow" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Leave without pushing.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: true,
            effects: [{ type: "modifyRelationship", npcId: "ai-hollow", axis: "respect", delta: 5 }],
          },
          {
            id: "c2",
            text: "\"Something happened to you out there.\"",
            requirementLabel: "Requires Perception 6",
            conditions: [{ type: "minStat", stat: "perception", value: 6 }],
            hiddenIfUnmet: true,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-hollow", axis: "suspicion", delta: 10 }, { type: "modifyRelationship", npcId: "ai-hollow", axis: "respect", delta: 3 }, { type: "setFlag", flag: "ai-flag-hollow-noticed" }],
            goTo: "n3",
          },
        ],
      },
      { id: "n3", speakerId: "ai-hollow", speakerName: "Hollow", expression: "worried", text: "...Careful. Keep guessing like that and I'll start guessing back.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-hollow-field",
    worldId: W,
    chapterId: C,
    title: "Hollow, Alone in the Field",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-hollow",
        speakerName: "Hollow",
        expression: "cold",
        text: "This isn't a good spot to linger. A party wiped here on launch day. I know because I was the only one who walked out.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-hollow-wipe-mentioned" }, { type: "startQuest", questId: "ai-q-hollow-past" }],
        choices: [],
        conditions: [{ type: "missingFlag", flag: "ai-flag-hollow-wipe-mentioned" }],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "There's a locket half-buried nearby, if you look closely.",
        isInnerMonologue: true,
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ai-scene-hollow-recruit",
    worldId: W,
    chapterId: C,
    title: "Asking Hollow to Party Up",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        text: "You could try asking Hollow to join you for the boss raid, now that they know you found the locket.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [{ type: "hasItem", itemId: "ai-item-hollow-locket", quantity: 1 }, { type: "missingFlag", flag: "ai-flag-hollow-recruited" }],
        choices: [
          {
            id: "c1",
            text: "\"You don't have to be alone for this one.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-hollow-recruited" },
              { type: "modifyRelationship", npcId: "ai-hollow", axis: "trust", delta: 20 },
              { type: "modifyRelationship", npcId: "ai-hollow", axis: "affection", delta: 8 },
              { type: "completeQuest", questId: "ai-q-hollow-past", outcome: "recruited" },
              { type: "unlockAchievement", achievementId: "ach-unlikely-ally" },
            ],
            goTo: "good",
          },
          {
            id: "c2",
            text: "Return the locket and leave it at that.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            effects: [{ type: "modifyRelationship", npcId: "ai-hollow", axis: "trust", delta: 8 }, { type: "completeQuest", questId: "ai-q-hollow-past", outcome: "respected-distance" }],
          },
        ],
      },
      { id: "good", speakerId: "ai-hollow", speakerName: "Hollow", expression: "worried", text: "...Fine. Once. Don't make me regret it.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-archivist-intro",
    worldId: W,
    chapterId: C,
    title: "The Archivist",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-arch",
        speakerName: "Archivist",
        expression: "neutral",
        text: "Welcome, player. I sell information the system doesn't strictly want you to have. Fair prices. Perfect accuracy. No further questions answered about what I am.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-archivist" }, { type: "unlockCodex", entryId: "ai-codex-archivist" }],
        conditions: [],
        choices: [
          { id: "c1", text: "\"Are you a player?\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [], goTo: "dodge" },
          { id: "c2", text: "Leave it alone.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: true, effects: [] },
        ],
      },
      { id: "dodge", speakerId: "ai-arch", speakerName: "Archivist", expression: "smile", text: "That question is outside what I'm permitted to sell an answer to. Ask me about the boss instead.", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-archivist-mystery" }], choices: [], conditions: [] },
    ],
  },

  /* ---------------------------- Utility / town scenes ---------------------------- */
  {
    id: "ai-scene-inn",
    worldId: W,
    chapterId: C,
    title: "Rest",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "You pay a few col for a real bed instead of the ground. It's a small mercy, but you take it.", isInterruption: false, effects: [{ type: "modifyStat", stat: "health", delta: 999 }, { type: "modifyStat", stat: "stamina", delta: 999 }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-item-shop",
    worldId: W,
    chapterId: C,
    title: "Item Shop",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: false,
        text: "The shop's wares, laid out on a cloth counter.",
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "buy-heal", text: "Buy Healing Crystal — 30 col", requirementLabel: "Requires 30 Col", conditions: [{ type: "minStat", stat: "col", value: 30 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -30 }, { type: "addItem", itemId: "ai-item-healing-crystal", quantity: 1 }], goTo: "n1" },
          { id: "buy-stamina", text: "Buy Stamina Draught — 25 col", requirementLabel: "Requires 25 Col", conditions: [{ type: "minStat", stat: "col", value: 25 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -25 }, { type: "addItem", itemId: "ai-item-stamina-draught", quantity: 1 }], goTo: "n1" },
          { id: "buy-teleport", text: "Buy Teleport Crystal — 200 col", requirementLabel: "Requires 200 Col", conditions: [{ type: "minStat", stat: "col", value: 200 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyStat", stat: "col", delta: -200 }, { type: "addItem", itemId: "ai-item-teleport-crystal", quantity: 1 }], goTo: "n1" },
          { id: "leave", text: "Leave", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-tavern",
    worldId: W,
    chapterId: C,
    title: "The Cracked Bell Tavern",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Half the tavern is trading rumors about the field boss. The other half is pretending not to listen for their own name on the day's casualty list.", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-town-of-beginnings" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-guild-board",
    worldId: W,
    chapterId: C,
    title: "Guild Recruitment Board",
    startNode: "n1",
    altEntryNodes: ["n1", "chosen"],
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: false,
        text: "Three banners are pinned to the board: Iron Vanguard, Hearthlight, Stonebreakers. Or you could tear none of them down and stay solo.",
        isInterruption: false,
        effects: [{ type: "startQuest", questId: "ai-q-guild-recruit" }],
        conditions: [{ type: "missingFlag", flag: "ai-flag-guild-chosen" }],
        choices: [
          {
            id: "c1",
            text: "Join the Iron Vanguard.",
            requirementLabel: "Requires having met Ryo",
            conditions: [{ type: "flag", flag: "ai-flag-met-ryo" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-vanguard" },
              { type: "modifyStat", stat: "combat", delta: 1 },
              { type: "modifyRelationship", npcId: "ai-ryo", axis: "loyalty", delta: 15 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "vanguard" },
            ],
            goTo: "chosen",
          },
          {
            id: "c2",
            text: "Join Hearthlight.",
            requirementLabel: "Requires having met Nell",
            conditions: [{ type: "flag", flag: "ai-flag-met-nell" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-hearthlight" },
              { type: "modifyStat", stat: "empathy", delta: 1 },
              { type: "modifyRelationship", npcId: "ai-nell", axis: "loyalty", delta: 15 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "hearthlight" },
            ],
            goTo: "chosen",
          },
          {
            id: "c3",
            text: "Join the Stonebreakers.",
            requirementLabel: "Requires having met Dask",
            conditions: [{ type: "flag", flag: "ai-flag-met-dask" }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-stonebreakers" },
              { type: "modifyStat", stat: "col", delta: 500 },
              { type: "modifyRelationship", npcId: "ai-dask", axis: "loyalty", delta: 15 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "stonebreakers" },
            ],
            goTo: "chosen",
          },
          {
            id: "c4",
            text: "Stay solo. You trust your own blade more than a banner.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [
              { type: "setFlag", flag: "ai-flag-guild-chosen" },
              { type: "setFlag", flag: "ai-flag-guild-solo" },
              { type: "modifyStat", stat: "discipline", delta: 1 },
              { type: "completeQuest", questId: "ai-q-guild-recruit", outcome: "solo" },
              { type: "unlockAchievement", achievementId: "ach-lone-swordsman" },
            ],
            goTo: "chosen",
          },
        ],
      },
      { id: "chosen", expression: "neutral", isInnerMonologue: true, text: "Your choice is posted. Whatever comes next on this floor, you won't be facing it as a total unknown anymore.", isInterruption: false, effects: [], choices: [], conditions: [{ type: "flag", flag: "ai-flag-guild-chosen" }] },
    ],
  },
  {
    id: "ai-scene-tutorial-quest",
    worldId: W,
    chapterId: C,
    title: "Training Quest",
    startNode: "n1",
    altEntryNodes: ["n1", "done"],
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "A system NPC runs you through the basics: sword skills draw from a stamina pool, timing your input during the skill's motion adds bonus damage. You drill it against a dummy until it's muscle memory.",
        isInterruption: false,
        effects: [
          { type: "setFlag", flag: "ai-flag-tutorial-complete" },
          { type: "modifyStat", stat: "swordSkill", delta: 2 },
          { type: "unlockCodex", entryId: "ai-codex-sword-skills" },
          { type: "sendMessage", npcId: "ai-kirei", messageId: "ai-msg-kirei-checklist" },
        ],
        conditions: [{ type: "missingFlag", flag: "ai-flag-tutorial-complete" }],
        choices: [],
      },
      { id: "done", expression: "neutral", isInnerMonologue: true, text: "You've already drilled this. The dummy has seen better days.", isInterruption: false, effects: [], choices: [], conditions: [{ type: "flag", flag: "ai-flag-tutorial-complete" }] },
    ],
  },
  {
    id: "ai-scene-hidden-shrine",
    worldId: W,
    chapterId: C,
    title: "The Forgotten Shrine",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "A perfectly circular clearing, moss-covered stones arranged in a ring that has nothing to do with any quest marker. It feels deliberate — like part of Aincrad the developers never meant players to find this early.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-found-shrine" }, { type: "completeQuest", questId: "ai-q-hidden-floor1-shrine" }, { type: "unlockCodex", entryId: "ai-codex-shrine-secret" }, { type: "addItem", itemId: "ai-item-beginner-ring", quantity: 1 }, { type: "unlockAchievement", achievementId: "ach-off-the-map" }],
        conditions: [],
        choices: [],
      },
    ],
  },
  {
    id: "ai-scene-vigil",
    worldId: W,
    chapterId: C,
    title: "The Vigil",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Candles, relit every day by hands nobody's ever caught in the act. Names are scratched into the stone beneath them — none you recognize, all clearly real people.", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-vigil" }], choices: [], conditions: [] },
    ],
  },

  /* ---------------------------- Boss Raid: Floor 1 ---------------------------- */
  {
    id: "ai-scene-boss1-prep",
    worldId: W,
    chapterId: C,
    title: "Raid Preparation — Sylvan Guardian",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "This is it. Whatever's waiting past this chamber decides whether Floor 1 opens up or closes on someone's name.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockCodex", entryId: "ai-codex-sylvan-guardian" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Focus fire the core once its bark plating breaks — high risk, fast kill.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-aggressive" }, { type: "triggerBattle", encounterId: "ai-enc-boss1" }],
          },
          {
            id: "c2",
            text: "Rotate guard duty so no one takes consecutive hits — slower, safer.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-cautious" }, { type: "triggerBattle", encounterId: "ai-enc-boss1" }],
          },
          {
            id: "c3",
            text: "Use analyze skills first to map its full attack pattern before committing.",
            requirementLabel: "Requires Intelligence 6",
            conditions: [{ type: "minStat", stat: "intelligence", value: 6 }],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-analyzed" }, { type: "modifyStat", stat: "threatLevel", delta: -5 }, { type: "triggerBattle", encounterId: "ai-enc-boss1" }],
          },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss1-aftermath",
    worldId: W,
    chapterId: C,
    title: "After the Guardian",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The Guardian's core dims and the chamber's roots retract into the walls. Floor 1's boss is down. Somewhere below, the announcement rings out across every player's HUD at once.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "addItem", itemId: "ai-item-floor1-unique", quantity: 1 }, { type: "unlockAchievement", achievementId: "ach-floor-pioneer" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "In the middle of the celebration, you notice someone's stamina bar in the corner of the party display flickering red. A decision has to be made in the next few seconds.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Break formation to cover them yourself.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            timerSeconds: 8,
            effects: [
              { type: "setFlag", flag: "ai-flag-zero-casualties" },
              { type: "modifyRelationship", npcId: "ai-kirei", axis: "trust", delta: 10 },
              { type: "modifyRelationship", npcId: "ai-toran", axis: "respect", delta: 10 },
              { type: "unlockAchievement", achievementId: "ach-zero-casualties" },
            ],
            goTo: "safe",
          },
          {
            id: "c2",
            text: "Trust the formation to hold and stay on the boss's attack pattern.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            timerSeconds: 8,
            effects: [{ type: "setFlag", flag: "ai-flag-raid-casualty" }, { type: "modifyRelationship", npcId: "ai-toran", axis: "respect", delta: -8 }],
            goTo: "cost",
          },
        ],
      },
      { id: "safe", expression: "neutral", isInnerMonologue: true, text: "It's close, but everyone's still standing when the boss's health hits zero. Floor 1, cleared. Nobody's name gets added to a list today.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch1-complete" }, { type: "goToScene", sceneId: "ai-scene-chapter-recap-trigger" }], choices: [], conditions: [] },
      { id: "cost", expression: "sad", isInnerMonologue: true, text: "The boss falls. So does someone else, a second too late for anyone to reach. Floor 1 is cleared. It doesn't feel like a victory in the way you expected.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch1-complete" }, { type: "goToScene", sceneId: "ai-scene-chapter-recap-trigger" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-chapter-recap-trigger",
    worldId: W,
    chapterId: C,
    title: "One Floor Down",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Ninety-nine floors left. The Town of Beginnings looks different now — less like a waypoint, more like the first room of somewhere you actually live.",
        isInterruption: false,
        effects: [{ type: "unlockAchievement", achievementId: "ach-one-floor-down" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ============================ Floor 2: Mistfallen Reach ============================ */
  {
    id: "ai-scene-floor2-arrival",
    worldId: W,
    chapterId: "ai-ch2",
    title: "Mistfallen Landing",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The teleport gate deposits you into cold air and thinner light. Floor 2 doesn't bother pretending to be friendly the way the Town of Beginnings did.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-floor2-arrived" }, { type: "unlockCodex", entryId: "ai-codex-mistfallen-warden" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ai-kirei",
        speakerName: "Kirei",
        expression: "neutral",
        text: "Beta knowledge runs out around here — this is as far as any of us actually got before launch. From here it's just us figuring it out live.",
        isInterruption: false,
        effects: [{ type: "changeLocation", mapId: "ai-map-town2", spawnId: "default" }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ai-scene-boss2-prep",
    worldId: W,
    chapterId: "ai-ch2",
    title: "Raid Preparation — Mistfallen Warden",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The Frozen Court's fog is thick enough to lose a party member three feet away. Whatever's waiting on that throne, you'll mostly be fighting it by sound.",
        next: "n2",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Stay tight in formation so nobody gets separated in the fog.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid2-tight" }, { type: "triggerBattle", encounterId: "ai-enc-boss2" }],
          },
          {
            id: "c2",
            text: "Spread out to flank it — riskier if the fog swallows someone alone.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid2-spread" }, { type: "triggerBattle", encounterId: "ai-enc-boss2" }],
          },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss2-aftermath",
    worldId: W,
    chapterId: "ai-ch2",
    title: "After the Warden",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The Warden's armor collapses into fog and old rust. Floor 2 clears. Somewhere below, the Town of Beginnings' bells ring for a floor most of its residents will never see.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ai-toran",
        speakerName: "Toran",
        expression: "smile",
        text: "Two down. Ninety-eight to go. I'm told that's supposed to sound discouraging.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-ch2-complete" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ============================ Floor 3: Ashen Hollow ============================ */
  {
    id: "ai-scene-floor3-arrival",
    worldId: W,
    chapterId: "ai-ch3",
    title: "Ashen Hollow Settlement",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The heat hits before the gate even finishes rendering. Floor 3 is built into rock that never quite cooled down.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-floor3-arrived" }, { type: "unlockCodex", entryId: "ai-codex-ashen-hollow-king" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ai-mei",
        speakerName: "Mei",
        expression: "worried",
        text: "I'm setting up shop wherever the party goes next — someone has to keep your gear from melting off you down here.",
        isInterruption: false,
        effects: [{ type: "changeLocation", mapId: "ai-map-town3", spawnId: "default" }],
        choices: [],
        conditions: [],
      },
    ],
  },
  {
    id: "ai-scene-boss3-prep",
    worldId: W,
    chapterId: "ai-ch3",
    title: "Raid Preparation — Ashen Hollow King",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Whoever's kept that vigil at the dungeon gate isn't here today. Just you, the heat, and a throne room built out of every blade that didn't make it out.",
        next: "n2",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Bait its cinder bat summons early, before it's at full strength.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid3-bait" }, { type: "triggerBattle", encounterId: "ai-enc-boss3" }],
          },
          {
            id: "c2",
            text: "Ignore the summons entirely and focus everything on the King.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-raid3-focus" }, { type: "triggerBattle", encounterId: "ai-enc-boss3" }],
          },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss3-aftermath",
    worldId: W,
    chapterId: "ai-ch3",
    title: "After the King",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The self-declared ruler of a hollow nobody wanted falls, ash settling over a throne that was never really his to begin with. Floor 3 clears.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Later, at the field's edge, the row of candles is lit again — whoever keeps that vigil already knows the floor is cleared.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-ch3-complete" }],
        choices: [],
        conditions: [],
      },
    ],
  },

  /* ============================ Floor 4: Verdant Spire ============================ */
  {
    id: "ai-scene-floor4-arrival",
    worldId: W,
    chapterId: "ai-ch4",
    title: "Canopy Landing",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Floor 4 doesn't have a ground floor worth mentioning — the whole settlement is built into the first great branch of something that used to be a tree and is now closer to a mountain.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-floor4-arrived" }],
        choices: [],
        conditions: [],
      },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "Rope bridges creak underfoot. Somewhere above, someone is laughing at how normal that sounds to them now.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town4", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor4-npc-intro",
    worldId: W,
    chapterId: "ai-ch4",
    title: "Sena Kurogane",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        speakerId: "ai-sena",
        speakerName: "Sena",
        expression: "smile",
        text: "New climbers! Good — most parties lose someone to the bridges before they even reach the field. Rule one: don't look down. Rule two: I'm serious, don't.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-met-sena" }, { type: "unlockCodex", entryId: "ai-codex-sena" }],
        conditions: [],
        choices: [
          { id: "c1", text: "\"You sound like you've fallen before.\"", requirementLabel: "Requires Perception 5", conditions: [{ type: "minStat", stat: "perception", value: 5 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-sena", axis: "respect", delta: 6 }], goTo: "n2" },
          { id: "c2", text: "\"Noted. Thanks for the warning.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-sena", axis: "trust", delta: 4 }] },
        ],
      },
      { id: "n2", speakerId: "ai-sena", speakerName: "Sena", expression: "shocked", text: "...Twice, actually. Both times someone's Guard skill happened to proc right under me. I never found out who. Kind of unnerving, not knowing who to thank.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-sena-secret" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss4-prep",
    worldId: W,
    chapterId: "ai-ch4",
    title: "Raid Preparation — Spire's Peak",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Verdant Warden's arena is the widest platform on the whole Spire — which mostly just means there's more room to fall.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-verdant-warden" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "Fight near the platform's edge — more room to dodge its slam attacks.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid4-edge" }, { type: "triggerBattle", encounterId: "ai-enc-boss4" }] },
          { id: "c2", text: "Fight near the center — safer footing, less room to maneuver.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid4-center" }, { type: "triggerBattle", encounterId: "ai-enc-boss4" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss4-aftermath",
    worldId: W,
    chapterId: "ai-ch4",
    title: "After the Warden",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Verdant Warden splits down its trunk and goes still. Floor 4 clears. Sena's already sketching the next set of platforms before the health bar finishes emptying.", next: "n2", isInterruption: false, effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }], choices: [], conditions: [] },
      { id: "n2", speakerId: "ai-sena", speakerName: "Sena", expression: "determined", text: "First complete map of the Spire. I'm putting your name on it, whether you like it or not.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch4-complete" }], choices: [], conditions: [] },
    ],
  },

  /* ============================ Floor 5: The Drowned Causeway ============================ */
  {
    id: "ai-scene-floor5-arrival",
    worldId: W,
    chapterId: "ai-ch5",
    title: "Causeway Landing",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Floor 5's gate opens onto a stilted platform over black water. The whole town smells like salt and something slightly wrong.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-floor5-arrived" }], choices: [], conditions: [] },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "A weathered trader's stall is the first thing you see. Its owner looks like he's been expecting you for a while.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town5", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor5-npc-intro",
    worldId: W,
    chapterId: "ai-ch5",
    title: "Bram Oyelaran",
    startNode: "n1",
    nodes: [
      { id: "n1", speakerId: "ai-bram", speakerName: "Bram", expression: "neutral", text: "Amphibious gear, fitted before you set one boot in that swamp. I've seen what the Causeway does to parties who skip that step. I'd rather not see it again.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-met-bram" }, { type: "unlockCodex", entryId: "ai-codex-bram" }], conditions: [], choices: [
        { id: "c1", text: "\"Again? What happened the first time?\"", requirementLabel: "Requires Empathy 5", conditions: [{ type: "minStat", stat: "empathy", value: 5 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-bram", axis: "trust", delta: 6 }], goTo: "n2" },
        { id: "c2", text: "\"I'll take the gear. Thanks.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-bram", axis: "respect", delta: 4 }] },
      ] },
      { id: "n2", speakerId: "ai-bram", speakerName: "Bram", expression: "sad", text: "...Lost my old party out there, launch week. Every discount I hand out since is me trying to make sure nobody else's story ends the same way. That's the whole reason for the shop, really.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-bram-secret" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss5-prep",
    worldId: W,
    chapterId: "ai-ch5",
    title: "Raid Preparation — The Drowned Court",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Sovereign's throne room is already ankle-deep in water before the fight even starts. That's clearly a hint about how the rest of it goes.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-drowned-sovereign" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "Keep to the shallows where footing is stable.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid5-shallow" }, { type: "triggerBattle", encounterId: "ai-enc-boss5" }] },
          { id: "c2", text: "Push into deeper water to cut off its retreat.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid5-deep" }, { type: "triggerBattle", encounterId: "ai-enc-boss5" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss5-aftermath",
    worldId: W,
    chapterId: "ai-ch5",
    title: "After the Sovereign",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The crown sinks before the rest of it does. Floor 5 clears, and the water across the whole causeway seems to settle, just slightly.", next: "n2", isInterruption: false, effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }], choices: [], conditions: [] },
      { id: "n2", speakerId: "ai-bram", speakerName: "Bram", expression: "smile", text: "Whole floor, cleared, and everyone who went in with you is still standing. That's not luck. That's the gear doing its job — and you doing yours.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch5-complete" }], choices: [], conditions: [] },
    ],
  },

  /* ============================ Floor 6: Gilded Quarter ============================ */
  {
    id: "ai-scene-floor6-arrival",
    worldId: W,
    chapterId: "ai-ch6",
    title: "Gilded Quarter",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Floor 6's gate opens onto real wealth — storefronts, polished plazas, a town that looks like it forgot it's inside a death game.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-floor6-arrived" }], choices: [], conditions: [] },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "Somebody with sharp eyes and sharper business sense is already sizing you up as a potential customer.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town6", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor6-npc-intro",
    worldId: W,
    chapterId: "ai-ch6",
    title: "Iris Vantille",
    startNode: "n1",
    nodes: [
      { id: "n1", speakerId: "ai-iris", speakerName: "Iris", expression: "smirk", text: "New money, new face, new mark, take your pick — whichever you are, welcome to the only floor in Aincrad where col still means something. I'm Iris. I make sure it stays that way.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-met-iris" }, { type: "unlockCodex", entryId: "ai-codex-iris" }], conditions: [], choices: [
        { id: "c1", text: "\"You're manipulating the market, aren't you.\"", requirementLabel: "Requires Perception 6", conditions: [{ type: "minStat", stat: "perception", value: 6 }], hiddenIfUnmet: true, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-iris", axis: "suspicion", delta: 10 }, { type: "modifyRelationship", npcId: "ai-iris", axis: "respect", delta: 5 }, { type: "setFlag", flag: "ai-flag-iris-noticed" }], goTo: "n2" },
        { id: "c2", text: "\"Good to know. I'll be careful with my col.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-iris", axis: "trust", delta: 3 }] },
      ] },
      { id: "n2", speakerId: "ai-iris", speakerName: "Iris", expression: "cold", text: "...Sharp. I like that in a customer and hate it in a witness. Keep it to yourself and we'll get along fine.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss6-prep",
    worldId: W,
    chapterId: "ai-ch6",
    title: "Raid Preparation — The Golden Magnate",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Magnate's chamber is lined with col spent by players who never got to spend it themselves. It's the least subtle boss arena you've seen yet.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-golden-magnate" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "Strip its plating fast before it can shed more col as a blinding burst.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid6-fast" }, { type: "triggerBattle", encounterId: "ai-enc-boss6" }] },
          { id: "c2", text: "Play patient and let its own hoard slow it down.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid6-patient" }, { type: "triggerBattle", encounterId: "ai-enc-boss6" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss6-aftermath",
    worldId: W,
    chapterId: "ai-ch6",
    title: "After the Magnate",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Magnate's iron core sputters out under a mountain of its own spent col. Floor 6 clears — and somewhere, market prices across the whole Quarter visibly shift.", next: "n2", isInterruption: false, effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }], choices: [], conditions: [] },
      { id: "n2", speakerId: "ai-iris", speakerName: "Iris", expression: "smile", text: "You just crashed half my inventory's resale value. I should be furious. Instead I'm impressed, which is somehow worse for my bottom line.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch6-complete" }], choices: [], conditions: [] },
    ],
  },

  /* ============================ Floor 7: Hollow Choir ============================ */
  {
    id: "ai-scene-floor7-arrival",
    worldId: W,
    chapterId: "ai-ch7",
    title: "Hollow Choir",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The teleport gate makes no sound arriving on Floor 7. Neither does anything else.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-floor7-arrived" }], choices: [], conditions: [] },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "Even your own footsteps sound like they're arriving a half-second late, from somewhere else.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town7", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor7-npc-intro",
    worldId: W,
    chapterId: "ai-ch7",
    title: "The Choirkeeper",
    startNode: "n1",
    nodes: [
      { id: "n1", speakerId: "ai-choirkeeper", speakerName: "Choirkeeper", expression: "neutral", text: "(...welcome. it's rare anyone stays long enough to be welcomed properly.)", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-met-choirkeeper" }, { type: "unlockCodex", entryId: "ai-codex-choirkeeper" }], conditions: [], choices: [
        { id: "c1", text: "\"Why do you stay here?\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-choirkeeper", axis: "trust", delta: 3 }], goTo: "n2" },
        { id: "c2", text: "Match their volume. Say nothing above a whisper.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: true, effects: [{ type: "modifyRelationship", npcId: "ai-choirkeeper", axis: "respect", delta: 6 }] },
      ] },
      { id: "n2", speakerId: "ai-choirkeeper", speakerName: "Choirkeeper", expression: "sad", text: "(...i could have kept climbing. i chose not to. someone has to listen for the ones who don't make it past this floor. it might as well be me.)", isInterruption: false, effects: [{ type: "startQuest", questId: "ai-q-choirkeeper-past" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss7-prep",
    worldId: W,
    chapterId: "ai-ch7",
    title: "Raid Preparation — The Hollow Chorus",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Dozens of voices, the Choirkeeper said, never given the chance to log out safely. You're not sure that makes this fight easier to walk into.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-hollow-chorus" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "Try to drown out the voices with noise and momentum.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid7-loud" }, { type: "triggerBattle", encounterId: "ai-enc-boss7" }] },
          { id: "c2", text: "Listen for the pattern in the silence between attacks.", requirementLabel: "Requires Perception 6", conditions: [{ type: "minStat", stat: "perception", value: 6 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid7-listen" }, { type: "triggerBattle", encounterId: "ai-enc-boss7" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss7-aftermath",
    worldId: W,
    chapterId: "ai-ch7",
    title: "After the Chorus",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The voices don't scream as they scatter. They just — stop, one at a time, like a room slowly emptying. Floor 7 clears.", next: "n2", isInterruption: false, effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }], choices: [], conditions: [] },
      { id: "n2", speakerId: "ai-choirkeeper", speakerName: "Choirkeeper", expression: "smile", text: "(...thank you. i think, for the first time since i got here, it's actually quiet. the good kind.)", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch7-complete" }], choices: [], conditions: [] },
    ],
  },

  /* ============================ Floor 8: The Iron Maze ============================ */
  {
    id: "ai-scene-floor8-arrival",
    worldId: W,
    chapterId: "ai-ch8",
    title: "Maze Camp",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Floor 8's gate opens onto a camp of tents pitched just outside a maze entrance nobody's mapped completely.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-floor8-arrived" }], choices: [], conditions: [] },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "Every tent wall here is chalked with somebody's failed route. A wiry figure is adding another line to a truly enormous diagram.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town8", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor8-npc-intro",
    worldId: W,
    chapterId: "ai-ch8",
    title: "Doc Renner",
    startNode: "n1",
    nodes: [
      { id: "n1", speakerId: "ai-doc-renner", speakerName: "Doc Renner", expression: "thinking", text: "Oh! New data point. Sorry — new person. Tell me, when you walked in, did the camp entrance feel like it was to your left or your right? It matters more than you'd think.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-met-doc-renner" }, { type: "unlockCodex", entryId: "ai-codex-doc-renner" }], conditions: [], choices: [
        { id: "c1", text: "\"You think the maze rearranges itself on purpose.\"", requirementLabel: "Requires Intelligence 6", conditions: [{ type: "minStat", stat: "intelligence", value: 6 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-doc-renner", axis: "respect", delta: 8 }], goTo: "n2" },
        { id: "c2", text: "\"Left, I think.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-doc-renner", axis: "trust", delta: 3 }] },
      ] },
      { id: "n2", speakerId: "ai-doc-renner", speakerName: "Doc Renner", expression: "shocked", text: "...Nobody's ever said that part out loud to me before. Yes. I do. I can't prove it. But yes.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-doc-renner-theory" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss8-prep",
    worldId: W,
    chapterId: "ai-ch8",
    title: "Raid Preparation — The Iron Architect",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The maze's center chamber doesn't look designed so much as accumulated — like something's been rebuilding it for a very long time.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-iron-architect" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "Hit it hard before it can rebuild its own armor mid-fight.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid8-fast" }, { type: "triggerBattle", encounterId: "ai-enc-boss8" }] },
          { id: "c2", text: "Let it rebuild, then punish the exposed frame underneath.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid8-patient" }, { type: "triggerBattle", encounterId: "ai-enc-boss8" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss8-aftermath",
    worldId: W,
    chapterId: "ai-ch8",
    title: "After the Architect",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Architect stops mid-rebuild, half-finished, and doesn't move again. Floor 8 clears — and for the first time, the maze's walls hold perfectly still.", next: "n2", isInterruption: false, effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }], choices: [], conditions: [] },
      { id: "n2", speakerId: "ai-doc-renner", speakerName: "Doc Renner", expression: "shocked", text: "It's not moving. The whole maze — it's not moving. I can finally finish the map. Twenty minutes. Give me twenty minutes. Actually, don't wait, just — go on ahead, I'll catch up.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch8-complete" }], choices: [], conditions: [] },
    ],
  },

  /* ============================ Floor 9: Skybreak Terrace ============================ */
  {
    id: "ai-scene-floor9-arrival",
    worldId: W,
    chapterId: "ai-ch9",
    title: "Skybreak Landing",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The gate opens onto wind that nearly takes you off your feet. Floor 9 is the highest town you've stood in yet.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-floor9-arrived" }], choices: [], conditions: [] },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "On a clear day, someone says, you can just make out the Town of Beginnings from here. You look anyway.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town9", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor9-npc-intro",
    worldId: W,
    chapterId: "ai-ch9",
    title: "Wren Castellan",
    startNode: "n1",
    nodes: [
      { id: "n1", speakerId: "ai-wren", speakerName: "Wren", expression: "smile", text: "Nine floors. I was on Floor 1 the same launch day you were, near enough — first cohort. Feels strange, doesn't it. Being one of the ones who's still climbing.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-met-wren" }, { type: "unlockCodex", entryId: "ai-codex-wren" }], conditions: [], choices: [
        { id: "c1", text: "\"Do you remember people who didn't make it this far?\"", requirementLabel: "Requires Empathy 6", conditions: [{ type: "minStat", stat: "empathy", value: 6 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-wren", axis: "trust", delta: 8 }, { type: "modifyRelationship", npcId: "ai-wren", axis: "affection", delta: 4 }], goTo: "n2" },
        { id: "c2", text: "\"We made it. That's what matters.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-wren", axis: "respect", delta: 3 }] },
      ] },
      { id: "n2", speakerId: "ai-wren", speakerName: "Wren", expression: "sad", text: "...All of them. Every one. It doesn't get easier to carry, but it gets easier to keep climbing anyway. I think that's the only version of okay available to any of us up here.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-wren-secret" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss9-prep",
    worldId: W,
    chapterId: "ai-ch9",
    title: "Raid Preparation — The Skybreak Sentinel",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Sentinel's arena is open to the sky on all sides. There's nowhere on this terrace the wind doesn't reach.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-skybreak-sentinel" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "Stay mobile and never let the storm settle on one spot.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid9-mobile" }, { type: "triggerBattle", encounterId: "ai-enc-boss9" }] },
          { id: "c2", text: "Hold ground and weather the storm together.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, importantChoice: true, effects: [{ type: "setFlag", flag: "ai-flag-raid9-hold" }, { type: "triggerBattle", encounterId: "ai-enc-boss9" }] },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss9-aftermath",
    worldId: W,
    chapterId: "ai-ch9",
    title: "After the Sentinel",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The storm the Sentinel carried breaks apart into ordinary wind. Floor 9 clears, and the terrace goes quiet enough to actually hear the view.", next: "n2", isInterruption: false, effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }], choices: [], conditions: [] },
      { id: "n2", speakerId: "ai-wren", speakerName: "Wren", expression: "determined", text: "One floor from the Gate. I didn't think I'd get this far when this started. Whatever's waiting up there — I'm glad I'm not walking in without you.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ch9-complete" }], choices: [], conditions: [] },
    ],
  },

  /* ============================ Floor 10: The Tenth Gate ============================ */
  {
    id: "ai-scene-floor10-arrival",
    worldId: W,
    chapterId: "ai-ch10",
    title: "Gatewatch",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "Gatewatch is quieter than every town before it. Not empty — quieter, the way a place gets when everyone in it is thinking about the same thing.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-floor10-arrived" }], choices: [], conditions: [] },
      { id: "n2", expression: "neutral", isInnerMonologue: true, text: "A vast stone approach is visible past the town's edge, leading to a gate that hasn't opened for anyone yet.", isInterruption: false, effects: [{ type: "changeLocation", mapId: "ai-map-town10", spawnId: "default" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-floor10-npc-intro",
    worldId: W,
    chapterId: "ai-ch10",
    title: "Ilyana Vasko",
    startNode: "n1",
    nodes: [
      { id: "n1", speakerId: "ai-ilyana", speakerName: "Ilyana", expression: "cold", text: "You're the party everyone's been talking about. Good. I need to know if that's earned before I let you anywhere near that gate.", next: "n2", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-met-ilyana" }, { type: "unlockCodex", entryId: "ai-codex-ilyana" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you respond?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          { id: "c1", text: "\"Ask me anything. I'll prove it.\"", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-ilyana", axis: "respect", delta: 6 }], goTo: "n3" },
          { id: "c2", text: "\"You don't have to test me. Just tell me what happened to the first attempt.\"", requirementLabel: "Requires Empathy 6", conditions: [{ type: "minStat", stat: "empathy", value: 6 }], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-ilyana", axis: "trust", delta: 10 }, { type: "startQuest", questId: "ai-q-ilyana-guilt" }], goTo: "n4" },
        ],
      },
      { id: "n3", speakerId: "ai-ilyana", speakerName: "Ilyana", expression: "neutral", text: "...We'll see. Talk's cheap up here. The gate's the only thing that actually grades you.", isInterruption: false, effects: [], choices: [], conditions: [] },
      { id: "n4", speakerId: "ai-ilyana", speakerName: "Ilyana", expression: "worried", text: "...I was supposed to be in that party. Pulled out at the last minute — cold feet, I told myself. None of them came back. I've been standing at this gate ever since, deciding if that makes me a coward or the only smart one.", isInterruption: false, effects: [{ type: "setFlag", flag: "ai-flag-ilyana-secret" }], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-ilyana-join",
    worldId: W,
    chapterId: "ai-ch10",
    title: "Asking Ilyana to Join the Raid",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        text: "You could ask Ilyana to join the party for the raid on the Gate itself.",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [{ type: "flag", flag: "ai-flag-ilyana-secret" }, { type: "missingFlag", flag: "ai-flag-ilyana-recruited" }],
        choices: [
          {
            id: "c1",
            text: "\"Come with us. Finish what you couldn't the first time.\"",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            effects: [{ type: "setFlag", flag: "ai-flag-ilyana-recruited" }, { type: "modifyRelationship", npcId: "ai-ilyana", axis: "trust", delta: 15 }, { type: "modifyRelationship", npcId: "ai-ilyana", axis: "loyalty", delta: 10 }, { type: "unlockAchievement", achievementId: "ach-unlikely-ally" }],
            goTo: "good",
          },
          { id: "c2", text: "Let her make her own choice about whether to come.", conditions: [], hiddenIfUnmet: false, isBluff: false, isSilence: false, effects: [{ type: "modifyRelationship", npcId: "ai-ilyana", axis: "respect", delta: 6 }] },
        ],
      },
      { id: "good", speakerId: "ai-ilyana", speakerName: "Ilyana", expression: "determined", text: "...Okay. Okay. This time I finish it.", isInterruption: false, effects: [], choices: [], conditions: [] },
    ],
  },
  {
    id: "ai-scene-boss10-prep",
    worldId: W,
    chapterId: "ai-ch10",
    title: "Raid Preparation — The Tenth Gate",
    startNode: "n1",
    nodes: [
      { id: "n1", expression: "neutral", isInnerMonologue: true, text: "The Gatekeeper waits at the base of a gate that's never opened for anyone. This is the hardest fight this climb has offered so far, and everyone in Gatewatch knows it.", next: "n2", isInterruption: false, effects: [{ type: "unlockCodex", entryId: "ai-codex-tenth-gatekeeper" }], choices: [], conditions: [] },
      {
        id: "n2",
        expression: "neutral",
        text: "How do you want to approach the fight?",
        isInnerMonologue: false,
        isInterruption: false,
        effects: [],
        conditions: [],
        choices: [
          {
            id: "c1",
            text: "Go in aggressive from the first bell — end it before it unseals its second weapon.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            timerSeconds: 10,
            effects: [{ type: "setFlag", flag: "ai-flag-raid10-aggressive" }, { type: "triggerBattle", encounterId: "ai-enc-boss10" }],
          },
          {
            id: "c2",
            text: "Play the long game — every phase costs it something, so let it burn out.",
            conditions: [],
            hiddenIfUnmet: false,
            isBluff: false,
            isSilence: false,
            importantChoice: true,
            timerSeconds: 10,
            effects: [{ type: "setFlag", flag: "ai-flag-raid10-patient" }, { type: "triggerBattle", encounterId: "ai-enc-boss10" }],
          },
        ],
      },
    ],
  },
  {
    id: "ai-scene-boss10-aftermath",
    worldId: W,
    chapterId: "ai-ch10",
    title: "The Tenth Gate Opens",
    startNode: "n1",
    nodes: [
      {
        id: "n1",
        expression: "neutral",
        isInnerMonologue: true,
        text: "The Gatekeeper falls. For a long moment nothing happens — and then, with a sound like the whole floor exhaling, the Tenth Gate begins to open.",
        next: "n2",
        isInterruption: false,
        effects: [{ type: "unlockAchievement", achievementId: "ach-floor-pioneer" }, { type: "unlockAchievement", achievementId: "ach-tenth-gate" }],
        choices: [],
        conditions: [],
      },
      {
        id: "n2",
        speakerId: "ai-toran",
        speakerName: "Toran",
        expression: "smile",
        text: "Ten floors. Whatever happens past this gate, you got this far by choosing who to trust, not just what to swing a sword at. That matters more than the number does.",
        next: "n3",
        isInterruption: false,
        effects: [],
        choices: [],
        conditions: [],
      },
      {
        id: "n3",
        expression: "neutral",
        isInnerMonologue: true,
        text: "Ninety floors left past this gate. For now, though — for the first time since the day logout disappeared — it feels less like a prison and more like a story you're actually telling.",
        isInterruption: false,
        effects: [{ type: "setFlag", flag: "ai-flag-ch10-complete" }],
        choices: [],
        conditions: [],
      },
    ],
  },
];
